### ISSUE TITLE
Q: Drop shadows...

### ISSUE THREAD

**Issue by Martii** [uracreative/works#1]
Hey there... had a question about some work you did a while back.

The icon at [/uracreative/works/blob/`d019c35`/QupZilla/SVG/icon-color.svg](https://github.com/uracreative/works/blob/d019c359c231e88b371e308b5cd721960bb3ad6b/QupZilla/SVG/icon-color.svg) shows a drop shadow in the vector editor I loaded it into briefly however every browser on every platform doesn't seem to show it.

Did I miss the boat somewhere on why it's not showing up?

Thanks mate.

**Comment by AnXh3L0** [comment]
Hello @Martii. I checked the icon you mentioned above and yes, it shows a drop shadow in the editor because that's how the logo is supposed to be. Apparently browsers don't play with it nicely.
