### ISSUE TITLE
I2P Style Guide

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#10]
Based on the same system we created Style Guides for Reproducible Builds and SecureDrop, we will implement a Style Guide for I2P as part of the OTF Usability Lab.

It should include the usual components tailored for I2P.

@LuisTepshi can you start setting up a repo with the same architecture we got from Reproducible Builds as a base? GitHub pages here should work. @AnXh3L0 can assist when needed.

**Comment by elioqoshi** [comment]
@eupiteco, can you add all the gray's from Open Color to the Style Guide?

**Comment by elioqoshi** [comment]
Also please use the same components withint the style guide as outlined (for example the download buttons have a different button style than the component buttons.)

**Comment by eupiteco** [comment]
**Summary of the last push**
1. All the SG buttons are now in the pill shape
1. Removed the gray line below the headers
1. Reduced the large and medium buttons height by 33%
1. Added the OC grays 
1. Changed 'SecureDrop' with 'I2P' in a few places where it was still showing up
---
**Contents that are missing**
1. I2P favicon
1. Text about alerts
1. Identihub-hosted SVGs, the raw SVGs from the `works/I2P` repo does not work2
1. Missing links:
    1. Assets SVG for donwlload
    1. Identihub page
    1. Contact / mailing list
---
Check it @ https://uracreative.github.io/i2p-styleguide/ my eyes may be missing some details after looking to this styleguides for some time now, fresh looks are welcome.

**Comment by eupiteco** [comment]
**Summary of the last push**
1. Added header and footer components
2. The alerts colors now match the I2P colors
3. Did some fixes in the overall components page layout

**Comment by elioqoshi** [comment]
The first implementation of the style guide is here:
https://ura.design/projects/i2p
