### ISSUE TITLE
SDR Makerspace WordPress Site Theme Customization

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#11]
Based on the brand identity for the SDR Makerspace we need to customize the website theme to match the identity we created:
http://sdrmaker.space/

SDR Makerspace on Identihub:
https://demo.identihub.co/project/esa-sdr-makerspace

**Comment by AnXh3L0** [comment]
What is specifically needed here? Editing the current WordPress theme to match the colors that are being used in the identity?

**Comment by elioqoshi** [comment]
Yeah but there is still no content on the site so let's wait for further details

**Comment by elkos** [comment]
At the moment we need adding the esa logo pointing to https://www.esa.int/esalogo/index.html and the libre space logo and link to https://libre.space under the marks "ESA Activity" "Implemented by LSF" respectfully.

Either at the home page at widget space.

**Comment by elioqoshi** [comment]
Cool. @AnXh3L0 can you address this by tomorrow? Ping me for the credentials

**Comment by AnXh3L0** [comment]
The ESA and Libre Space logo have been added to the bottom of the page and are linked to their respective websites.

**Comment by AnXh3L0** [comment]
@elkos is there anything left here to do?

**Comment by elioqoshi** [comment]
Closing this as finished.
