### ISSUE TITLE
Briar UX & User Testing

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#12]
We are working in the next months with Briar on their next release as part of the OTF grant. Details here: 
https://code.briarproject.org/briar/briar/boards

Anything tagged UX and Usability needs input from our end. Please track any major milestones or blockers here. Project coordination happens on the Briar GitLab and Mattermost. @rskikuli please keep track of project progress so we are on time for all deliverables.

**Comment by elioqoshi** [comment]
For context, most of this work has been tracked on Briar's own GitLab:

Power Management Improvements: https://code.briarproject.org/briar/briar/issues/1261
Image Attachments: https://code.briarproject.org/briar/briar/issues/1243
Adding Contacts Remotely: https://code.briarproject.org/briar/briar/issues/1235
Dark Theme: https://code.briarproject.org/briar/briar/issues/1252
Tor Bridges: https://code.briarproject.org/briar/briar/issues/1270

@RenataGegaj can you update us on what testing sessions are remaining?

**Comment by RenataGegaj** [comment]
Latest update: We conducted usability testing for power management improvements feature that has ben added to Briar lately. You can find the test results on this issue [https://code.briarproject.org/briar/briar/issues/1261]

**Comment by elioqoshi** [comment]
Thanks! Marking that deliverable as complete.

**Comment by elioqoshi** [comment]
The only thing left here is doing Usability Testing for the Remote Add Contacts and Image attachments after these have been implemented in the protocol. That might take some time

**Comment by RenataGegaj** [comment]
We conducted several iterations of usability testings for Remote Add Contacts and Image attachments. The finalized work for Remote Add Contacts here: https://code.briarproject.org/briar/briar/issues/1235
and for Image attachments here: https://code.briarproject.org/briar/briar/issues/1243

**Comment by elioqoshi** [comment]
This work is wrapped up so we can close this.
