### ISSUE TITLE
Rust Latam Conference Visual Identity

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#13]
We will be helping the Rust Latam Conference with Visual Identity. For this, Ura will be a sponsor of the conference. 

We need to deliver the usual deliverables:

- Word mark
- Icon
- Icon + Word mark = logo
- Colours
- Fonts

Additionally, we should cater to create at least:

- A2 Poster
- T-Shirt
- Badge & Lanyards
- Twitter Banner
- Facebook Banner
- Social Media Avatar

Brief (from @barrosgeraldo ): 

- We see Latin America as an extremely diverse region in cultures, languages, people and countries.
- One of the best ways to represent this diversity is through colors, see our Twitter icon that contains in the background the colors that represent the flag colors of all Latin American countries.
- See the examples we have created and examples of other conferences.
- Feel free to create something totally unique in your creativity and design.

___________

I will create the brand for the conference, push it to Identihub and continue work on the poster and T-Shirt afterwards. @AnXh3L0 can continue from there on and prepare the remaining deliverables.

**Comment by spastorino** [comment]
Hey, thanks for helping us with this :). Feel free to ping any of us if you need some info.

**Comment by elioqoshi** [comment]
@spastorino sure!

Here are some logo proposals beforehand:

![image](https://user-images.githubusercontent.com/5436686/42583139-b933317e-8530-11e8-8007-5ec8ffa6cd16.png)

![image](https://user-images.githubusercontent.com/5436686/42583205-cae95ab0-8530-11e8-9d1c-e4862bc946ec.png)

**Comment by spastorino** [comment]
It's cool, BUT ...

1. The map is only including South America, you should go up and include Central America and Mexico.
2. The colors in the map make me think just in Brazil, which is also a huge country in South America, so it could feel just as a brazilian thing :).

**Comment by sebasmagri** [comment]
Hi!

First of all I'd also like to thank you for helping us with this!

I share the opinion from @spastorino though in that Latin America is astoundingly diverse and we'd like that to be reflected in the conference branding. Besides the observation to include Central America, Mexico, and to the possible extent also the Caribbean, I'd like to remind you to check out the previous work that Geraldo shared with you, used in the [twitter account](https://twitter.com/RustLatamConf), for an example on the kind and diversity of vibrant colors that we think could help us reflect both the diversity and the personality of Latin American people...

Again, thanks a lot for your help folks!

**Comment by sebasmagri** [comment]
Please take a look at [this map](https://en.wikipedia.org/wiki/Latin_America#/media/File:Latin_America_(orthographic_projection).svg) of what's _officially_ part of Latin America. Some English speaking countries are not formally considered part of it, but in general we're very kind and still consider them part of Latin America.

**Comment by spastorino** [comment]
Another thing, we can't talk about RustConf because it's a trademark. I'd put a line with Rust Latam and then maybe a line saying Montevideo 2019.

**Comment by elioqoshi** [comment]
Thanks for the detailed feedback. The cultural context was our main concern and this has been addressed. We should have updates very soon :)

**Comment by barrosgeraldo** [comment]
Hi @elioqoshi, thank you so much for support us here, we are looking to have our visual identity ready by the end of this month, let us know if the deadline will have to be extended, so we can work better with our strategies and plans. Cheers! :tada:

**Comment by elioqoshi** [comment]
@barrosgeraldo I'm going on vacations 5th August so it would be appreciated if we can extend it to 4th August just in case. Once the logo, colors and fonts are pinned down, the deliverables don't take much time

**Comment by elioqoshi** [comment]
So how about this? This puts an emphasis on the brand system rather the logo:
![image](https://user-images.githubusercontent.com/5436686/43371112-838719dc-938b-11e8-85ab-8ee0cf7afce4.png)


It can be flexible and adapt for many situations:
![image](https://user-images.githubusercontent.com/5436686/43371151-5d2966ae-938c-11e8-8047-abd76f207e98.png)

Frames:
![image](https://user-images.githubusercontent.com/5436686/43371173-d7f1483e-938c-11e8-8254-801a36c01971.png)

![image](https://user-images.githubusercontent.com/5436686/43371258-50e7f14c-938e-11e8-946f-6cd57ff7bfd9.png)


What do you think?

**Comment by spastorino** [comment]
@elioqoshi this looks great :heart:

**Comment by sebasmagri** [comment]
I really like it too! Great work @elioqoshi  and team...

**Comment by AnXh3L0** [comment]
Hello everyone, 
Below you will find a zip file that contains most of the assets in the SVG, PDF and PNG formats.
Please note that this is not final and changes could happen at anytime based on your feedback.
[RUST LATAM Assets.zip](https://github.com/uracreative/works/files/2254441/RUST.LATAM.Assets.zip)

Cheers,
Anxhelo

**Comment by elioqoshi** [comment]
Please also keep in mind that details are not included as there are apparently none yet and we can do them as we get closer to the event @barrosgeraldo ?

**Comment by spastorino** [comment]
Cool, this is great!!!

**Comment by elioqoshi** [comment]
Thanks! @barrosgeraldo can you let us know if these are good to go? If so we can push the sources to our repo here

**Comment by AnXh3L0** [comment]
Hi @barrosgeraldo, the assets are now in the [repo](https://github.com/uracreative/works/tree/master/Rust%20LATAM).
Cheers,
Anxhelo

**Comment by spastorino** [comment]
Hi @elioqoshi,

I saw we already have a lot of useful things designed like the badge and lanyard. First, we would need to include gold and silver sponsors on lanyards, would that be possible?.
We would also need t-shirts, we need to include gold and silver sponsors too. You can check out sponsors here https://rustlatam.org/#our_sponsors but I can also provide vectorial logos and stuff.

**Comment by elioqoshi** [comment]
@spastorino Thanks. @ergish can help with creating these assets. @AnXh3L0 could you guide him on this?

**Comment by elioqoshi** [comment]
Also, is this somehow urgent @spastorino ? Should be no problem by the end of the year or do you need it quicker done?

**Comment by ergish** [comment]
Hi @spastorino,
If you can provide the vectorial versions of the logos it would help us a lot!

**Comment by elioqoshi** [comment]
@ergish @AnXh3L0 and me did them, hence you should check in with Anxhelo :)

**Comment by spastorino** [comment]
@elioqoshi end of the year is ok.

@ergish I can provide vectorial versions of the logo, will talk with @elioqoshi on private to see how I can send you that

**Comment by spastorino** [comment]
@ergish just in case you didn't see it I've sent all the logos over email.
There's no rush for now on this but can you give me an idea about more or less how much it will take to you?.
Thanks a lot.

**Comment by ergish** [comment]
@spastorino we got the logos. Thank you for that! I think by the end of the month we will send you mockups for each version of the T-shirt design.

About the logos added on the lanyard, we wouldn't suggest that because of the thin size of the lanyard ribbon and the logos of the sponsors and the rust logo would be equal in size and that might be confusing. But we can add the logos in the badges. Please let me know what you think. 
The badges will be delivered on the same day as the T-shirts.

**Comment by ergish** [comment]
Hi there,
@sebasmagri 

Please, check out the links below:
Badge: https://presentator.ura.design/sq-al/e2usDSTd?v=0&s=1&m=preview
T-shirts: https://presentator.ura.design/sq-al/phV0TU3j?v=0&s=1&m=preview

Turn on the "Fit to Screen" option in the right corner of the top menu for a better view. Also, to view the other versions check the top menu. 

One of the T-shirt designs does not include the sponsors, but that's just an option. Please choose which elements you like the most and if there are any changes you want to recommend, feel free to propose them by leaving comments on the images in our Presentator.

**Comment by ergish** [comment]
Hi there,
@spastorino 

Please, check out the links below:
Badge: https://presentator.ura.design/sq-al/e2usDSTd?v=0&s=1&m=preview
T-shirts: https://presentator.ura.design/sq-al/phV0TU3j?v=0&s=1&m=preview

Turn on the "Fit to Screen" option in the right corner of the top menu for a better view. Also, to view the other versions check the top menu.

One of the T-shirt designs does not include the sponsors, but that's just an option. Please choose which elements you like the most and if there are any changes you want to recommend, feel free to propose them by leaving comments on the images in our Presentator.

**Comment by spastorino** [comment]
@ergish this is great, I love it :). I like the first t-shirt design. Anyway, going to check with the rest of the team and will get back to you.

**Comment by spastorino** [comment]
@ergish we like the first t-shirt, the black one. Can you try building a new design of that one but also including the Rust logo?. We are not sure if we want it or not but it may be nice to try out :).

**Comment by ergish** [comment]
@spastorino This will be the T-shirt design with the full horizontal logo.

![t-shirt-design-1 1---mockup](https://user-images.githubusercontent.com/44442505/50444602-b8b90680-0909-11e9-8f3e-6276f1106bae.jpg)

Let us know if you agree on keeping the updated design of the badges with the sponsors, and also which files will you need so we can deliver them.

**Comment by ergish** [comment]
@spastorino I'm glad you like it! 
So, the thing is, if we use another color (one of the visual identity colors) some of the squares won't be visible because they will have the same color as the t-shirts. In my opinion, the best would be to use the white/gray color for the t-shirt if we are using the same design, or a black t-shirt with another design like option 3 and 4 in the presentator in the link above with a more organized shape for the staff.

Also are you sure about the sponsor logos in both staff and merchandised t-shirt?

Let us know what you think and we'll deliver what is best for you!

**Comment by spastorino** [comment]
What about going with this same design as is for regular t-shirts and same design in grey for staff and without logos on staff t-shirts.
Also, just in case if you can provide black t-shirts without logos too would be great.

**Comment by ergish** [comment]
@spastorino 
In the image below there's a preview of the T-shirts with and without the logos.
![preview](https://user-images.githubusercontent.com/44442505/50491802-75978a00-0a14-11e9-9648-eb14acc49614.jpg)

**Comment by spastorino** [comment]
@ergish great, but I'm not too convinced because colors between them is similar. Can we make the last try with STAFF in white?.

**Comment by ergish** [comment]
@spastorino
Here's a preview of the white T-shirts. In any case, both designs, with the white and black writing (with and without sponsors) will be delivered to you.
![preview1](https://user-images.githubusercontent.com/44442505/50539425-49008100-0b80-11e9-90ff-2fc802b21b26.jpg)

**Comment by spastorino** [comment]
Love this, I think that's all then. We have the t-shirts, badges and lanyards.
Thanks a lot. Please send me the source files when you can :heart: :heart: :heart:

**Comment by ergish** [comment]
@spastorino 
In the zip file you'll find:
- Badge + Lanyard with the Font Family that will be used in the badges.
- T-shirt designs and all their alternations.

[Rust Latam 2019 - Delivery 2.zip](https://github.com/uracreative/works/files/2720779/Rust.Latam.2019.-.Delivery.2.zip)

Please, let us know if you have any question!

Warm Regards and Happy New Year! :)

**Comment by spastorino** [comment]
@ergish I have a last request, we want to design stickers :). Maybe we already have some kind of asset design that "applies" and it's not a lot of work?.
Let me know if you guys can do something.

**Comment by ergish** [comment]
Hi @spastorino
Yes, why not. If you guys have any specific request or any element you want to add in the sticker, let us know. Otherwise we will design something using the visual elements we have.

**Comment by spastorino** [comment]
Just go ahead freely and with your own ideas, you have been building great stuff that I don't want to ruin :).

**Comment by ergish** [comment]
[Rust Latam 2019 - Delivery 3 - Stickers.zip](https://github.com/uracreative/works/files/2772914/Rust.Latam.2019.-.Delivery.3.-.Stickers.zip)
@spastorino in the zip folder there are 6 sticker alternatives. You can use whichever you like best.

**Comment by spastorino** [comment]
Cool, thanks so much for this @ergish !!!

**Comment by ergish** [comment]
Cheers! :)

**Comment by mayela** [comment]
Hi @ergish. @elioqoshi told me that you are guy for my request. I had create this template for RustLatam social media, but @spastorino told me about is the incorrect arrangement of colors. Can you help me, please? Thanks in advance.
![rust-latam-social-media](https://user-images.githubusercontent.com/665952/53035419-fda97700-343a-11e9-816c-f8181e649685.png)

**Comment by elioqoshi** [comment]
@mayela hi! SImply don't use any yellow squares behind the logo so the contrast is fine there :)

**Comment by ergish** [comment]
Hello @mayela 
Yeah, the colors are ok. I would suggest not using the logo on the colorful background because of the contrast. But even avoiding the yellow squares behind the logo, as @elioqoshi said, it works just fine.

**Comment by mayela** [comment]
Thanks @elioqoshi and @ergish!

**Comment by AnXh3L0** [comment]
Hello @spastorino ,

One month until the conference, hope things are looking good for you. Is there any sneak peek on the printed materials? :D

**Comment by spastorino** [comment]
Not yet :). A lot of things are going to be done soon. Will keep you posted. Thanks a lot for your work and interest in this.

**Comment by spastorino** [comment]
Hi, everyone, we have a last request. We need to add more sponsors to the t-shirts. That would be the final version. So for the black t-shirt with logos we need to put those. Sharing a link to the logos in a bit.

@ergish we need this urgent, because we've figured that the t-shirt printing company needs all this for monday. We weren't expecting that, sorry for asking about this so late :(. Are you able to do it quickly?.

**Comment by ergish** [comment]
Hi @spastorino 
Unfortunately, I will be busy until Monday and not available to work. I can work on Monday and deliver the files in the same day, is that ok?

**Comment by elioqoshi** [comment]
@spastorino I'm sorry but it's Friday afternoon and we don't expect people to work on weekends. Please coordinate accordingly with the printing company. We will be able to work on Monday again.

**Comment by spastorino** [comment]
@ergish @elioqoshi yeah, don't worry, I wasn't expecting you to work during the weekend :). On monday is ok, and I'm very sorry to push you on this :(. Will send the logos today.

**Comment by mayela** [comment]
Hi guys! 
Thanks for your support, here is the zip with all sponsors' logos. 
If you need something else just let me know. Great weekend.

[logos-sponsors-rustlatam.zip](https://github.com/uracreative/works/files/2946827/logos-sponsors-rustlatam.zip)

**Comment by elioqoshi** [comment]
@mayela can you please attach again? I don't see anything

**Comment by mayela** [comment]
@elioqoshi I'd uploaded the file again. Thanks!

**Comment by mayela** [comment]
@elioqoshi sorry for the delay, here are the logos
[logos-sponsors-rustlatam.zip](https://github.com/uracreative/works/files/2947782/logos-sponsors-rustlatam.zip)

**Comment by spastorino** [comment]
@elioqoshi @ergish there are some wyeworks logos, png shouldn't be on the zip but you will figure out what to do :). There are two versions one to use on dark backgrounds and one to use on white.

**Comment by elioqoshi** [comment]
@spastorino on another note. would we be able to have short description on your website just like the other sponsors? https://rustlatam.org/#our_sponsors

**Comment by spastorino** [comment]
@elioqoshi definitely. I was also planning on mentioning you on stage and in other places.

**Comment by spastorino** [comment]
We need to also add Facebook to the T-shirt.
Here you have the list of logos updated and this is final now 
[rust-latam-tshirts-logos.zip](https://github.com/uracreative/works/files/2948428/rust-latam-tshirts-logos.zip)

**Comment by ergish** [comment]
Hi @spastorino in this folder you'll find the T-shirt and Badge files with the added sponsors. You didn't mention the badge but I included it anyway. The mockup files are not updated, only the print files.
About facebook, I added the logo of "Facebook Open Source" just like the other logos. Or did you want to add a Facebook Profile?
Let us know, please.

[Rust Latam 2019 - Delivery 4 - T-shirts + Badge.zip](https://github.com/uracreative/works/files/2952129/Rust.Latam.2019.-.Delivery.4.-.T-shirts.%2B.Badge.zip)

**Comment by spastorino** [comment]
Hey @ergish, thank you very much for doing this so fast. It looks great.

I may have a very last tiny request but I'm going to check everything today and let you know.

@elioqoshi we have added the description of Ura to the website.

Thank you very much guys!

**Comment by apiraino** [comment]
Hello @ergish, during the last sync confcall we discussed the possibility of printing also posters for the conference, we would like to have a quote from local printshops for that.

But first I think we need to update the design deliverables and we need some advice from you folks. I think we need:

- An updated design that includes the sponsors
- A new deliverable with a size suitable to be printed on a large sheet of material. Not sure about the standard conference rollup size, perhaps something around 80x180 cm

Can you guys let us have your thoughts on this? Thanks!

**Comment by spastorino** [comment]
@ergish I think you guys have already built something like this, in the original deliverable was on poster folder if I recall correctly. It's just that this should include sponsors also and all of them probably separated by gold, silver and bronze. Going to talk now with @apiraino so we can also give you the rest of the sponsors logos.

**Comment by apiraino** [comment]
ok @spastorino this should an updated list of our silver + gold sponsors ([I've updated the archive you uploaded 3 days ago](https://github.com/uracreative/works/issues/13#issuecomment-471177931)), theregfore this archive replace the previous one.

[rust-latam-sponsor-logos.zip](https://github.com/uracreative/works/files/2958212/rust-latam-sponsor-logos.zip)

Let me know if it's ok!

**Comment by ergish** [comment]
@apiraino @spastorino 
Hi guys, so the new logos, separated by gold, silver, bronze, beside the posters, should be also in the badges and the T-shirts right?

**Comment by ergish** [comment]
The Pyxis logo seems to be a vector file so it's perfectly fine.

**Comment by apiraino** [comment]
> @apiraino @spastorino
> Hi guys, so the new logos, separated by gold, silver, bronze, beside the posters, should be also in the badges and the T-shirts right?

Hi @ergish yes, I confirm that the sponsors names should be also on badhes and tshirts.

Let me know if you need anything else, thanks!

**Comment by ergish** [comment]
@apiraino @spastorino 
In this folder you'll find the updated design of:
* T-shirts
* Badges
* A3 Poster 
* Roll Up Poster

I had to make some changes on the final layout of the design because of the added sponsors. In my opinion, the new design looks even better.

Let me know if you need anything else!
[Rust Latam 2019 - Delivery 5 - T-shirts + Badge + Posters.zip](https://github.com/uracreative/works/files/2962892/Rust.Latam.2019.-.Delivery.5.-.T-shirts.%2B.Badge.%2B.Posters.zip)

**Comment by apiraino** [comment]
Great job, the new designs look gorgeous! We'll have a look at them during our meeting.

thanks! :+1:

**Comment by spastorino** [comment]
@ergish hey just saw all this, impressive work :heart:.

One minor detail, in the rollup design, aren't sponsor logos too small?. Given that we have a LOT of space, can't we put the word Gold and gold sponsors after that, Silver and silver sponsors and so on and make them a bit bigger?. You're the one that knows about how things look, I have no clue ;), take this as a suggestion but as an idea it may be a good idea to emphasize gold a bit more than silver and silver a bit more than bronze.

And meanwhile you're at this thing, the file is 0,80m x 1,8m it's better if it can be 0,8m x 2m.

Thanks a lot guys!!!

**Comment by elioqoshi** [comment]
@spastorino 

> One minor detail, in the rollup design, aren't sponsor logos too small?. Given that we have a LOT of space, can't we put the word Gold and gold sponsors after that, Silver and silver sponsors and so on and make them a bit bigger?.

You are absolutely right, it's not even a minor detail. We should fix this. @ergish I'd propose using 30%-40% of the rollup height for sponsors. They need to be readable from meters away afterall.

> suggestion but as an idea it may be a good idea to emphasize gold a bit more than silver and silver a bit more than bronze.

Definitely. 

> And meanwhile you're at this thing, the file is 0,80m x 1,8m it's better if it can be 0,8m x 2m.

If 0,8m x2m is the requirement we will do that, sure

**Comment by elioqoshi** [comment]
@spastorino, ironically, and amazingly how we never noticed is that we didn't include our own Ura logo in the deliverables lol

So we will update these with that too.

**Comment by spastorino** [comment]
@elioqoshi yeah, our idea was that you were one of the important sponsors too so please include you everywhere. The issue is that t-shirts are, unfortunately already being printed :(. But for the rest rollup, badges, etc we can still include you.

**Comment by elioqoshi** [comment]
It seems the reason we were not included is because @ergish just went ahead with the list of logos you sent, which didn't include Ura. But it could also mean that this would not need being mentioned, I don't know, some miscommunication happened. No big deal though.

Cool, thanks. Let's update the other ones.

**Comment by apiraino** [comment]
> It seems the reason we were not included is because @ergish just went ahead with the list of logos you sent, which didn't include Ura

This is partly also my fault, so please accept my apologies.

**Comment by elioqoshi** [comment]
> This is partly also my fault, so please accept my apologies.

No worries at all. @ergish joined our team after the Rust Latam work started so he was not aware of all details like I was :)

**Comment by ergish** [comment]
@spastorino @apiraino 

Hi there, 
Yes, I totally agree with the fact that the sponsor's logos can be bigger. Please, check out the new posters and badges.

Notice that in the Roll Up Banner I didn't want to combine the sponsors of different categories (gold/silver/bronze) in the same rows. So, because of the banner's width, I can not make the logos bigger than the attached version. Let me know what you think.
[Rust Latam 2019 - Delivery 6 - Badge + Posters.zip](https://github.com/uracreative/works/files/2977784/Rust.Latam.2019.-.Delivery.6.-.Badge.%2B.Posters.zip)

**Comment by spastorino** [comment]
@ergish this looks better. The posters are fine, at some point we need to hand you the text we are going to use. For the rollups that goes without text. It's just conference logo + sponsors. So we probably need sponsors logos to be bigger.

**Comment by ergish** [comment]
@spastorino Yes, if you can provide the text that would be great!
In the attached folder I have added another rollup with bigger logos. We can use this one for the rollups that go without text.
[Rust Latam 2019 - Delivery 6 - Badge + Posters.zip](https://github.com/uracreative/works/files/2977908/Rust.Latam.2019.-.Delivery.6.-.Badge.%2B.Posters.zip)

**Comment by spastorino** [comment]
Yeah, this is cool. We will get back to you in some hours about the text and all that.

**Comment by spastorino** [comment]
@ergish [here](https://docs.google.com/document/d/1vWisLFL_hsEYZczViva7QYdF-p1ioMwrottZoJuSBjA) is the exact text and QR we want to use for the posters.

**Comment by spastorino** [comment]
@ergish did you have a change to go over the text?. Let me know if trying to use the text in a way like that gives you troubles we may be able to change that.

**Comment by spastorino** [comment]
@ergish btw, besides the posters thing, I've asked in previous comments, we have badges on pdf but we need the printing company to change where it says name and company and use there the actual attendee data. Can you also send us the ai or source file of the badge?.

/cc @elioqoshi

**Comment by elioqoshi** [comment]
@spastorino We took off yesterday from work. We are addressing these today asap.

**Comment by ergish** [comment]
@spastorino the PDF files we have sent can be opened and edited in Illustrator so it's the same as having the ai file.

**Comment by apiraino** [comment]
ok thanks @ergish I'll try to open them in Inkscape and edit the Lorem Ispum text

**Comment by spastorino** [comment]
@ergish that would work great for the badges because that stuff is done by the printing company here. But can you send the poster with the text?, none of us have Illustrator unfortunately. If it's easy for you ... would be greatly appreciated :smile: :heart:

**Comment by ergish** [comment]
@spastorino @apiraino I sent the PDF versions only because usually, who are going to print them, would work better with the PDF versions. I am adding the text now on the posters. I will send them shortly in PDF and SVG, the posters and the badges.

**Comment by apiraino** [comment]
@ergish ok then: thank you so much!

**Comment by ergish** [comment]
@spastorino @apiraino 
Now the zip contains PDF and SVG formats of the posters and the badge template.
The text in the posters is replaced.
Maybe the design can be rechecked (@elioqoshi let us know what you think and if you have any idea for a rearrangement of the poster components). 
However, everything is editable. Cheers!
[Rust Latam 2019 - Delivery 7 - Badge + Posters with Text.zip](https://github.com/uracreative/works/files/2989269/Rust.Latam.2019.-.Delivery.7.-.Badge.%2B.Posters.with.Text.zip)

**Comment by ergish** [comment]
Also, please be careful about attaching the Fonts folder (Montserrat font) in the package for printing.

**Comment by spastorino** [comment]
This has reached to an end. Thanks so much for your work, we have gave you a special mention on stage too and said that you were the ones that made the design as cool as it is.

I have placed what you have on this repo on our Google Drive and added the updates you have been pushing to this issue. If it's useful for you to update the repo with the final stuff, I have that tidy up and can send to you I guess. Let me know.

**Comment by AnXh3L0** [comment]
Hey @spastorino, hope you had a fantastic conference. Sorry for the delay on this, we were all travelling the past week.

> If it's useful for you to update the repo with the final stuff, I have that tidy up and can send to you I guess.

That'd be great actually, thank you in advance.

**Comment by elioqoshi** [comment]
Thanks @spastorino it has been great working on this! I look forward to next year's edition :)

@ergish @AnXh3L0 could we add Rust Latam to our projects portfolio on our website as well?

**Comment by elioqoshi** [comment]
@ergish @AnXh3L0 ping regarding the website portfolio :)
Closing this, thanks everyone!
