### ISSUE TITLE
SustainOSS Brand Support & Redesign

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#14]
We are helping SustainOSS ( https://sustainoss.org ) with support to refresh their brand system and unify their messaging behind a single mission.

**Comment by elioqoshi** [comment]
For this we are starting with a Brand System to address the first issues.

SustainOSS Phase 6: Brand System
+++++++++++++++++++++++++++++

Observations:
-------------------

    SustainOSS has inconsistent branding across mediums 

    In more official mediums referred to as SustainOSS, in more casual mediums and verbal communication as Sustain. People avoid pronouncing the OSS after Sustain because it seems tiresome.

    The SustainOSS.org website directly brings the user to the SustainUK website, not showing any information about the Sustain Initiative itself.

    SustainUK is branded after the country it's held in, SustainOSS was branded after a city it was held in. During communication, the city seemed prioritized over the year. SustainSF has been referred to as such even after event without the year, sometimes confusing people that it would be an upcoming event.

    SustainOSS has a primary teal color and a dark blue color for its brand. SustainUK has adopted another color palette based on Halloween season in London.

    Sub-brands usually work as another word put behind the main brand. In SustainOSS it happens that a full word is merged together with an acronym without any space between. This strengthens the perception that SustainUK and SustainOSS are separate initiatives.

    SustainUK has a different logo lockup of SustainOSS giving more importance to the place it's held in rather than the SustainOSS brand itself (together with the last points this creates difficulties for newcomers to establish the relation between SustainUK and SustainOSS).



Proposal:
-------------

The problem with 'Sustain' as a brand is that it's a verb and not a noun, Due to that it sounds like a Call to Action or almost like a campaign (Sustain Open Source Software!! ' Sustain [the] United Kingdom!!). While Sustain on its own might be a bit awkard to use in every day scenarios (you basically use a verb as a noun/name).However it has proven to be a more elegant solution in non-formal communications as the majority of people involved, refer to it as 'Sustain' in any case. (as a comparison, it takes approximately 0.7 seconds to pronounce 'Sustain' while it takes 1.2 seconds to pronounce 'SustainOSS'. That's half a second!) Due to the fact that people refer to things either in their complete name (e.g: Open Source Initiative) OR acronyms (e.g: OSI) it feels counter-intuitive to refer to a name which has both like SustainOSS. As "Sustain Open Source Software" is very long, the remaining option which would hit the sweet spot would be simply "Sustain". While not bulletproof to confusions, it most likely would lessen current confusion and provide a base for consistency in upcoming mediums.

Sustain should be an umbrella organization bringing people from different projects to work on a common goal. It seems to work more like an alliance rather a thing on its own. Folks from Open Collective, Stickermule, Google, Mozilla, Gitcoin and co meet to discuss the future of Open Source. It feels sometimes like the events have more importance than Sustain itself which makes it more difficult to grow and allow people to contribute as Sustain. To ensure community health, it's important to allow a clear contribution path for Sustain.

In order to distinguish certain Sustain projects, it might be worthwhile creating sub-brands, starting from Sustain itself which could be named "Sustain Initiative". That would leave space for the events which should be prioritized by the nature of it, rather than the place it's in. "Sustain Summit" would be a good alternative which is flexible and has a more classic naming structure (e.g Sustain Summit 2018). Unless there are more than 1 Summit every year, this is a solution which would cover most use cases. If there are more than 1 Summit every year, it should be considered to append the Location after the name (e.g Sustain Summit - London 2018) .

**Comment by elioqoshi** [comment]
Please note that this is an introduction to the work we propose to do so we can discuss it in the call today.

**Comment by jdorfman** [comment]
I like `summit`.

> "Call to Action or almost like a campaign (Sustain Open Source Software!! ' Sustain [the] United Kingdom!!)." 

great point, I already see this being an issue:

![image](https://user-images.githubusercontent.com/398230/42697651-954f45ea-8670-11e8-87dd-d387d27214b9.png)

**Comment by BenJam** [comment]
Thanks @elioqoshi for putting this together. I am particularly excited to see you pick up on: 

> It feels sometimes like the events have more importance than Sustain itself which makes it more difficult to grow and allow people to contribute as Sustain

To me Sustain is a community of people working continuously to highlight, work through and propose solutions to some of the challenges that we have worked through. Some as part of the event(s) and others that are picked up elsewhere. I think that Sustain would have a greater impact if it were possible to use the website to:

a) understand the challenges that have been identified and 'catch up' on our shared understanding and vocabulary
b) find resources that might help you as a maintainer, contributor or user of open source
c) find others that are actively working in this space, or on specific subsets of problems and work with them.
d) communicate progress and publish new resources throughout the year to the rest of the open course community.

Obviously this goes beyond the scope that has been identified above but I like to include statements like this in case they set off any ideas and/or lead us to include pathways for them in the future. I  see a fair degree of overlap in the above 👍 

to be more specific:

* I think the current site needs to prioritise the next event, but provide a clear route to 'catch up' and be at a point where a new attendee can jump into conversations on the day.
* The report from last year's event is hidden, and I think an overview (intro, context and recommendations sections) could provide much of the 'catch up' material. I can re-write as needed. 
* I think we should include scope for 'working groups' type pages to provide an introduction to a number of distinct areas (we have them from the previous event)

Happy to work on this with you and the rest of the group. Maybe the next useful step would be a page description diagram and architecture? 

PS on the design front, I have little to provide other than, let's keep it positive and not bind make anything too gimmicky re. geography, time of year etc.

**Comment by elioqoshi** [comment]
Thanks @BenJam !

Addressing your comments:

>To me Sustain is a community of people working continuously to highlight, work through and propose solutions to some of the challenges that we have worked through. Some as part of the event(s) and others that are picked up elsewhere.

Totally agree. However the main website should be a "hub" where anyone can quickly navigate to all various layers of Sustain, no matter if the events or other Sustain initiatives. It needs to be flexible and expandable. The fact that Sustain only is about SustainUK right now, doesn't mean it would be in a similar fashion in the future. So we have to cater to allow any contributors to find out about contribution pathways beyond an event like SustainUK.

>I think the current site needs to prioritise the next event, but provide a clear route to 'catch up' and be at a point where a new attendee can jump into conversations on the day

Exactly. I think we are on the same page more or less.

> Happy to work on this with you and the rest of the group. Maybe the next useful step would be a page description diagram and architecture?

Sounds good. Although this might go a bit beyond the Brand System scope of this step we can start working on the high-level view of the page and what the message will be it should get across

> PS on the design front, I have little to offer other than: let's keep it positive and not make anything too gimmicky re. geography, time of year etc.

Indeed. Hence I'm unsure about the current color palette of the SustainUK website.

**Comment by jdorfman** [comment]
> However the main website should be a "hub" where anyone can quickly navigate to all various layers of Sustain, no matter if the events or other Sustain initiatives.

Exactly. I envision building sustainoss.org out to be the go-to destination for those who are interested in sustainability and want to contribute to the Open Source community without having to code. In addition to info on our events, it will also have best practices, blog posts, articles/reports, etc.

_From our vision/mission statement:_

![image](https://user-images.githubusercontent.com/398230/42823267-04b80ea2-8992-11e8-910e-511ff7287e58.png)

**Comment by elioqoshi** [comment]
To recap our conversation in the call:

- the umbrella 'SustainOSS' should become "Sustain" as OSS is kind of redundanct in practice as we have been seeing people refer to it as "Sustain" anyway.
- the annual Sustain events should be called Summits and focus on the year, not the location. The locations are not really important for the storytelling aspects as of now, they only serve as a logistical detail for this group of people to meet who have the same mission, same values and same philosophy from Sustain, no matter where. This would result in the upcoming event called "Sustain Summit 2018" and put the location (London, UK) into the same hierarchy priority as the date (25th October). The location should not be part of the brand. Sustain Summit is a moving event afterall
- this strategy would leave space for independent Sustain Events on a smaller scale (Meetups) to happen independently, disattaching Sustain from being centrally responsible for those events, rather representatives being responsible. e.g: Sustain Meetup Los Angeles #3 
- the color scheme and brand for the Summit would be based on the overal Sustain Brand. That means that it will be part of the same family, but can have looser interpretations and illustrations specifically for the edition (like GitHub Universe branding in relation to GitHub, maybe closer even): https://githubuniverse.com/

**Comment by jdorfman** [comment]
> the umbrella 'SustainOSS' should become "Sustain"

Can we keep the domain?

> the color scheme and brand for the Summit would be based on the overal [sic] Sustain Brand.

OK so let's get moving =)

**Comment by elioqoshi** [comment]
So folks, after a very nice design session with @jdorfman I present to you the logo and brand proposal for Sustain, including Summit and Meetups, a color palette which works within this system and a font choice for the brand as there was none before.

Attached you can get the PDF or you can view it via our Presentator and also comment on it!
https://presentator.ura.design/en/bazOJAH6

Looking forward to your feedback!

PDF: 
[Sustain Brand System.pdf](https://github.com/uracreative/works/files/2216229/Sustain.Brand.System.pdf)

**Comment by jdorfman** [comment]
@elioqoshi getting an error 

![cloudapp annotation 2018-07-23 at 3 00 18 pm png](https://user-images.githubusercontent.com/398230/43105267-29ee7ae8-8e89-11e8-9102-90c36f4b6f77.png)

**Comment by elioqoshi** [comment]
It should work now @jdorfman but it's the same really as the PDF. @piamancini and @BenJam and co. would love to have your feedback.

**Comment by jdorfman** [comment]
Perfect timing: https://github.com/sustainers/website/issues/152#issue-344250991

**Comment by coderberry** [comment]
@elioqoshi 

I tried to leave a comment in the slides but it didn't seem to work for me.

Regarding the slide with the metaphors, I do like what you have. The one that you landed on though doesn't really resonate with me as "sustainability". To me, sustainability is a slow growth that can weather any conditions. I think of trees or bridges or solid structures with the intent of surviving adversity.

Regarding the circle, fonts, colors, etc. I love it!

**Comment by BenJam** [comment]
@elioqoshi thanks for putting this together. My honest feedback is that the circle makes me think of lifebouys and the thunderbolt makes me think of electrical warnings. But that's just me.

I'm with @coderberry on stability, strength and resilience as the main touchpoints. That said I do think the emphasis on the events could be considered an intermittent 'spark' over the ongoing work the community are doing. I wonder whether there's something in that. 

I'll have a think about any alternate themes this w/e and replace this comment with them if anything comes up.

**Comment by jdorfman** [comment]
@BenJam on the call yesterday @piamancini had a concern with the lighting/thunderbolt. @elioqoshi is going to swap it with something else. =)

**Comment by elioqoshi** [comment]
@BenJam Thanks for the feedback. My male bias might have gone overboard with the Thunderbold :)
From what I gathered from the call we liked the circle however.

I worked on a less aggressive one here:

![image](https://user-images.githubusercontent.com/5436686/43355632-010ac1f6-9260-11e8-991a-e6ae7aa4b86a.png)

Not totally going to the tree direction @coderberry suggested, but having the plant analogy. What do you think?

**Comment by elioqoshi** [comment]
Slight alternation:

![image](https://user-images.githubusercontent.com/5436686/43355684-ccb80318-9260-11e8-9295-740239c72943.png)

**Comment by abitrolly** [comment]
While you are at it, please don't kill previous website. Its color scheme a link to report is easy to remember for someone like me, who occasionally refers other people to it.

**Comment by elioqoshi** [comment]
As decided in the last call, we have a winner! You can find the final exported logos here on our Identihub: 
https://demo.identihub.co/sustain

Please note that Identihub is under constant development so you might come across bugs. It's inhouse open source software on our servers however :)

Notes from the last call:
https://github.com/sustainers/events/issues/10

**Comment by elioqoshi** [comment]
Soon also in this repo. Ping @AnXh3L0

**Comment by AnXh3L0** [comment]
The assets are now in the repo, you can find them [here](https://github.com/uracreative/works/tree/master/Sustain). 
PS. Updating it at the moment to fix a small issue with some assets.

**Comment by elioqoshi** [comment]
Closing this, thanks for the great collaboration! @jdorfman if you need anything else, feel free to open an issue.
