### ISSUE TITLE
Logo for TurkuSec

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#15]
We are helping TurkuSec with a new logo:
https://demo.identihub.co/turkusec

https://turkusec.fi/

The Information Security Association of Turku 

@AnXh3L0 can we push the assets in the repo?

**Comment by AnXh3L0** [comment]
Yes, the assets are now in the repo, [here](https://github.com/uracreative/works/tree/master/TurkuSec).

**Comment by elioqoshi** [comment]
Thanks! Closing
