### ISSUE TITLE
 RustFest Rome visual identity 

### ISSUE THREAD

**Issue by marianaballa** [uracreative/works#16]
We will have to work on a visual identity for RustFest Rome (https://rome.rustfest.eu/).  Deadline for this is early October.

**Comment by AnXh3L0** [comment]
A short brief for the identity would be:
We have to keep the Roman vibe and the colors used in the EU main page for Rust: https://rustfest.eu
For the logo we would use the main symbol of RustFest EU but adopted for Rome (RustFest EU as an umbrellla brand).

Assets needed:
Logo
T-shirt Design
Web Assets (illustrations)
Mascot (Rust crab)
Social Media assets
Identihub Project page
Lanyard + Badge

**Comment by elioqoshi** [comment]
This is finished, thanks everyone involved!

A lot of discussions where held here:
https://github.com/RustFestEU/brand/issues/2

Also a blog post referencing our tshirt designs:
https://blog.rustfest.eu/tshirts-rome

Closing this as wrapped up.
