### ISSUE TITLE
Thunderbird "Preferences" UX Redesign 

### ISSUE THREAD

**Issue by marianaballa** [uracreative/works#18]
Following discussion on [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1498332), within the next two months we will be working together with the Thunderbird UX team on redesigning the "Preferences" option for Thunderbird. 

Discussion will take place on the #thunderbird channel on our Mattermost (https://chat.ura.design/) and on [Bug 1498332](https://bugzilla.mozilla.org/show_bug.cgi?id=1498332) on Bugzilla. 

Deadline: late January 2019

**Comment by elioqoshi** [comment]
Usability Study is finished and last tweaks are being made. This is good to go to be added to the website Thunderbird case study

**Comment by elioqoshi** [comment]
This is wrapped up, we just need to write a short blog post about it. Project: https://ura.design/projects/thunderbird
