### ISSUE TITLE
Librefox Branding

### ISSUE THREAD

**Issue by AnXh3L0** [uracreative/works#19]
Librefox (a modded Firefox browser that aims to improve privacy and security) is going to have a new website soon and it also needs a logo.

The leader of the project will also probably be at FOSDEM so a close meet-up will also work to gather some ideas.

The project resides here https://github.com/intika/Librefox

**Comment by elioqoshi** [comment]
Are you working on this @AnXh3L0 ?

**Comment by AnXh3L0** [comment]
I am working on the website at the moment, wanted to leave the logo for a bit later since FOSDEM is near and we can meet the main developer there to discuss.

**Comment by AnXh3L0** [comment]
We met with the main dev at FOSDEM this year but there is still no answer from Mozilla about the trademarks, so we can't carry on with this at the moment.

**Comment by AnXh3L0** [comment]
Still no answer from Mozilla, this is pending.

**Comment by AnXh3L0** [comment]
@intika please let us know if you have any update as I didn't receive an answer on Signal.

**Comment by AnXh3L0** [comment]
Closing this for the moment because of the uncertain future of Librefox.
