### ISSUE TITLE
Enigmail New Logo

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#2]
I talked with Patrick, the developer of Enigmail about potential design improvements of Enigmail. We agreed on starting off with the redesign of the logo. In the following are proposals of mine for the new enigmail logo:

![image](https://user-images.githubusercontent.com/5436686/37596350-2e141b02-2b7c-11e8-9a21-ebdfabfe4297.png)

**Comment by elioqoshi** [comment]
An alternative with solid icon instead of stroked:
![image](https://user-images.githubusercontent.com/5436686/37596742-7169e58e-2b7d-11e8-82f5-71ee7dfe1061.png)

Font used is Fira Sans Medium, which should make consistency with Mozilla and Thunderbird better

**Comment by elioqoshi** [comment]
New icons proposed:

![image](https://user-images.githubusercontent.com/5436686/37599737-b9827720-2b85-11e8-8602-652de046e25e.png)

**Comment by pbrunschwig** [comment]
First of all sorry for the delay -- I was really really busy with the Enigmail 2.0 release.

I like the logo & icons very much.

**Logo:** 
- I prefer the "alternative" logo - blue foreground with filled lock. I just think that the clamp (I'm not sure if that's the right term) is a little bit too thick.
- Furthermore, the blue color should better match the blue color on the top part of Enigmail web site https://enigmail.net/

** Icons **
I like that they match the logo; again, the clamp is a little too thick for me.

**Comment by elioqoshi** [comment]
@pbrunschwig thanks for the feedback.

I adapted the logos based on your feedback. The clamp is a bit thinner now. I would advise not to make it thinner than that as it would be unbalanced with the other part of the icon and would not look good on smaller sizes.

![image](https://user-images.githubusercontent.com/5436686/38333730-bbd42cf4-3859-11e8-8eb4-af28e6b3d30d.png)

**Comment by pbrunschwig** [comment]
Great thanks -- I think we can go for this :-)

Would you recommend to put the white on blue icon on the web site and use the blue on white version elsewhere, or is it better to use the identical icon everywhere?

**Comment by elioqoshi** [comment]
![image](https://user-images.githubusercontent.com/5436686/38354951-af243500-38bb-11e8-9e0e-60d8b35341a2.png)

First step would be updating the logo on the website as it is, but I hope that we get the chance to redesign the website as well :)

**Comment by pbrunschwig** [comment]
Yes, that's what I meant ;-) And yes, we can talk about re-designing the web site. It's on Joomla, and I used the free Purity III theme (which is quite OK for a start).

Do you have the logos and icons as SVG?

**Comment by elioqoshi** [comment]
We will update the icons with the new lock and export them by tomorrow and let you know.

**Comment by elioqoshi** [comment]
@pbrunschwig they are ready here:
https://demo.identihub.co/project/enigmail/

Soon uploading them also to our repo

**Comment by pbrunschwig** [comment]
Great, many thanks!!

**Comment by elioqoshi** [comment]
@pbrunschwig here also in the repo :)
https://github.com/uracreative/works/tree/master/Enigmail

Let me know if you want any license file in the folder for the things. Consider the rights of the work transferred to you. Please note that some of the icons (pencil and attachment) are based on Material Design icons licensed under Apache License Version 2.0:
https://github.com/google/material-design-icons

P.S: Try adding some vertical margins to the logo on the website, as right now it's touching the edges of the menu bar

**Comment by pbrunschwig** [comment]
> Let me know if you want any license file in the folder for the things. Consider the rights of the work transferred to you. 

Thanks! The web site is under the Creative Commons Attribution-ShareAlike License.

> P.S: Try adding some vertical margins to the logo on the website, as right now it's touching the edges of the menu bar. 

Yes, I noticed it too and fixed it.

> Also let me know if you need help with the favicon

I did create a 128x128 favicon, but somehow it's not picked up. If you have any idea why, I'd be grateful for tips.
