### ISSUE TITLE
Rufus+ Blood Donation - Logo

### ISSUE THREAD

**Issue by ergish** [uracreative/works#20]
We're working on the logo for Blood Donation:
https://github.com/opensourcedesign/jobs/pull/372

Also the discussion in the forum:
https://discourse.opensourcedesign.net/t/jobs-material-design-including-logo-and-assets/863

**Comment by elioqoshi** [comment]
Asking whether that's the name or they would like to explorer another name as "Blood Donation" is super generic.

**Comment by elioqoshi** [comment]
@ergish Any update on this?

**Comment by ergish** [comment]
Still nothing new on this one. We need a new name for it and it seems I can't come up with a name. Any ideas?

**Comment by elioqoshi** [comment]
I don't think all 3 of us should spend time on coming up with a new name, so please check with the developer of the project on a few names and we can move forward with this.

**Comment by ergish** [comment]
Just sent some random ideas for the name in the forum:
https://discourse.opensourcedesign.net/t/jobs-material-design-including-logo-and-assets/863

**Comment by AnXh3L0** [comment]
We kinda agreed to go on with the "Rufus+" name, will update on the progress.

**Comment by elioqoshi** [comment]
Proposal from my side:

![image](https://user-images.githubusercontent.com/5436686/53631011-c2b0fb80-3c11-11e9-8f9c-2bb7ee674620.png)

**Comment by ergish** [comment]
Presentation of 4 logo proposals including the logo above:
[RufusPlus - Logo Draft 1 - Presentation.pdf](https://github.com/uracreative/works/files/2931166/RufusPlus.-.Logo.Draft.1.-.Presentation.pdf)

**Comment by ergish** [comment]
So we agreed on the icon and the colors:
The final logo, with the SVG, PNG exports and the fonts needed:
[RufusPlus Delivery.zip](https://github.com/uracreative/works/files/2952363/RufusPlus.Delivery.zip)

**Comment by elioqoshi** [comment]
This is delivered, thanks!
