### ISSUE TITLE
Briar Design System & Style Guide

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#21]
As part of the Open Tech Fund Usability Lab we will be creating a style guide for Briar, including Logo Assets, Colors and Components. The base for this will be our usual Jekyll style guides (like SecureDrop, I2P) with some improvements on styling and layout, taking inspiration from the EOS Design System: https://www.eosdesignsystem.com

This work includes a cleaned up logo lockup without changing the typeface and glyph shape.

**Comment by elioqoshi** [comment]
@AnXh3L0 let us know when the initial repo is up

**Comment by AnXh3L0** [comment]
The initial repo is up, it's located here uracreative/briar-styleguide. I will continue to modify the layouts, assets and more in the following days.

**Comment by elioqoshi** [comment]
Thanks @AnXh3L0 
As discussed, the style guide needs to be done in Hugo, not Jekyll (like all of our other style guides) so let us know when the migration is done.

**Comment by AnXh3L0** [comment]
Yes, I have proceeded to migrate it to Hugo, shall be in the repo earlier today.

**Comment by elioqoshi** [comment]
@AnXh3L0 do you mean later today? As the latest commit is 6 days ago

**Comment by AnXh3L0** [comment]
Yes, my bad, later today.

**Comment by elioqoshi** [comment]
> Yes, my bad, later today.

Let's not be too optimistic with estimates if it means that we miss them (like this one)

**Comment by elioqoshi** [comment]
@onweru is helping us with this conversion

**Comment by elioqoshi** [comment]
@onweru can you update us on the progress of this?

**Comment by AnXh3L0** [comment]
The Briar style guide system is being worked on and the current state of it is visible on this website: https://briar-styleguide.netlify.com/

At the moment, a draft version of the dark theme is working and some sections are still missing.

**Comment by AnXh3L0** [comment]
The style guide process is towards the end, dark theme has been fixed and branding page was added.

**Comment by elioqoshi** [comment]
After @akwizgran's final comments are implemented and a few other small tweaks, this is ready to go:
https://briar-styleguide.netlify.com/

We should wrap it up and eventually plan a separate effort to do some copywriting work and UI copy guideline section as well.

**Comment by elioqoshi** [comment]
@AnXh3L0 there are also some small issues with the actual color label color contrast ratio. You can detect them yourself with the Accessibility dev tools as well:

![image](https://user-images.githubusercontent.com/5436686/66732492-78a51f00-ee5c-11e9-8753-e6df56c67a59.png)

**Comment by elioqoshi** [comment]
We might also want to add an illustration sub-section in the design section.

**Comment by AnXh3L0** [comment]
The comments from @akwizgran have been resolved and the changes have been pushed to the repo. The contrast has also been fixed and the illustration sub-section has been added to the design section.

**Comment by elioqoshi** [comment]
Illustrations also added in Figma:
https://www.figma.com/file/G3OJOk3fs1VNUxYazj4Yb46A/Briar-Design-System?node-id=251%3A0

**Comment by AnXh3L0** [comment]
Illustrations are also pushed to the page.

**Comment by elioqoshi** [comment]
This is ready now. 
Latest feedback from the Briar team has been incorporated as well.

Preview here: https://briar-styleguide.netlify.com/
Repo here: https://briar-styleguide.netlify.com/

Migration to Briar's GitLab can start anytime soon.

**Comment by elioqoshi** [comment]
@AnXh3L0 I am awaiting Michael's response to migrate the style guide to Briar's GitLab and publish it. We can close this issue afterwards.

**Comment by akwizgran** [comment]
Sorry for the slow follow-up @elioqoshi @AnXh3L0. The style guide looks great. Thanks for all your work on this.

I'll migrate the repo to code.briarproject.org. Is https://github.com/uracreative/briar-styleguide the current repo URL?

**Comment by elioqoshi** [comment]
@akwizgran Thanks! Yeah that is the current one.

**Comment by akwizgran** [comment]
@elioqoshi cloned to https://code.briarproject.org/briar/briar-styleguide
