### ISSUE TITLE
Tech Policy Card Game Product Design

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#23]
Finally Product Design for an actual meat space product :)

We are collaborating with @georgiamoon from Simply Secure to design the visuals of the cards and overall branding. @ergish is leading this effort from our side and @AnXh3L0 and me will be helping with the process. @RenataGegaj could eventually even do some Playability Testing afterwards 😛 

https://github.com/georgiamoon/techpolicycardgame/issues/3

**Comment by elioqoshi** [comment]
@ergish can you update us on the status of your explorations for this?

**Comment by ergish** [comment]
Hello there,

I've been researching, gathering ideas and playing around with the design of the cards layout and the icons of the cards categories. I think we should focus on the Logo and the Visual Guidelines first. After that, we can safely proceed with the illustrations of each card. :)

@georgiamoon @elioqoshi do we have a final name for the card game? Also, if have any ideas about the design, the colors, the illustration style or something that might resemble the product we want to create, please add it here. :)

**Comment by elioqoshi** [comment]
How about **Traxx** or **Trax** ?

Coming from Tracking as a wordplay and adding the xx at the end :)

**Comment by elioqoshi** [comment]
The Illustration style is probably too comical, but I like the layout and design system of Exploding Kittens:
https://explodingkittens.com/

**Comment by elioqoshi** [comment]
Started with some explorations, based on the stereoscopic duotone color and the idea of a grid-node (Tracks?)

![image](https://user-images.githubusercontent.com/5436686/53037356-45032800-347a-11e9-9cb1-b39aaf943dbb.png)

**Comment by elioqoshi** [comment]
Some good inspiration can be found here: 
https://www.pinterest.com/pin/327496204130684629

**Comment by elioqoshi** [comment]
2 quick card layout ideas:

![image](https://user-images.githubusercontent.com/5436686/53040753-77b11e80-3482-11e9-8c32-391bbdb12c50.png)

**Comment by elioqoshi** [comment]
Side Idea: As many card games have some quote or fun fact underneath written, it would be maybe nice to have a Fun Fact for every card related to some IRL event.

**Comment by elioqoshi** [comment]
For other color palettes, good inspiration here: https://www.instagram.com/colours.cafe/?hl=en

**Comment by Raphseck** [comment]
Hey guys!
Can i help with illustrations?

**Comment by elioqoshi** [comment]
This has never took off so closing this until there are new concrete plans.
