### ISSUE TITLE
Nile Logo & Brand Guidelines

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#25]
https://nile.shopping/

> Nile is a decentralized and commission-free shopping platform that promotes local economies. All the money you pay for goods or services goes directly to the seller.

Marco from Nile reached out asking whether we could contribute with design efforts at Nile. I think that it's a great project and we should get involved! Let's start with creating a logo and basic brand guidelines for Nile.

@ergish it would be great if you could lead the branding direction.

**Comment by ergish** [comment]
@elioqoshi 
Of course! I'm gathering all the information I need to come up with two logo concepts for the moment.

**Comment by elioqoshi** [comment]
Thanks! Please note that this is not in a rush and we have to prioritize some other projects at the moment and wrap them up first :)

**Comment by huhn511** [comment]
Hi guys, how are you doing? I'm a member of the Nile team, just want to ask what are first steps for getting this started! Would love to get this running with you! Thanks!

**Comment by elioqoshi** [comment]
@huhn511 Hi! We haven't received some follow-up on this since you reached out to us but we would be happy to start working on it. Do you have any vision or specifics you'd like Nile to look like or do you prefer for us to come up with something?

**Comment by huhn511** [comment]
Hi @elioqoshi! 

Oh sorry! We have made some first design results with a contributing designer. We thought you don't have much time for a pro bono project, so we decided to make some work first. We would love to get some feedback for it!  
All things are just suggestions and can be changed.

We would like to have something with the earth and the Nile river in the logo - but we are also open for new suggestions ;-) 

Here are the first logo results: 
![logo_1](https://user-images.githubusercontent.com/10562055/55249381-39123f00-524c-11e9-9efe-8cd676ecff74.png) ![logo_2](https://user-images.githubusercontent.com/10562055/55249382-39123f00-524c-11e9-9cb7-41281b7b5dfb.png) ![logo_3](https://user-images.githubusercontent.com/10562055/55249384-39aad580-524c-11e9-9715-01592a9b8620.png)

We will prepare all the thinkings and results in a document, which we can use for inspiration. 

Do you prefer this issue as communication tool or do you prefer an instant messenger?

Thanks for your time and have a nice weekend!

**Comment by huhn511** [comment]
Hi guys,
how are you doing? 

Here is some information about the actual state of the Nile CI. Would be nice if you can help with the logo and give us some feedback! (: 

[https://medium.com/@svreiser/empowering-local-economies-a-case-study-5de1fc38305a
](https://medium.com/@svreiser/empowering-local-economies-a-case-study-5de1fc38305a
)
Let us know if you need anything else.
Thanks!

**Comment by marcocastignoli** [comment]
Hey @ergish, my idea for the logo is to rappresent [glocalization](https://en.wikipedia.org/wiki/Glocalization) and the nile river. 

In this idea I wanted to rappresent the `simultaneous occurrence of both universalizing and particularizing tendencies in contemporary social, political, and economic systems. (from wikipedia)` using the Tao, that stands for the balance between the opposite. And the river to rappresent the nile river. However I'm not very satisfied with my result

![](https://user-images.githubusercontent.com/10562055/55249384-39aad580-524c-11e9-9715-01592a9b8620.png)

We are open to new suggestions! This is a list of the things that we would like to see in our logo, in order by importance!
* glocalization
* nile river
* feeless
* decentralization / federation
* community driven project
* privacy
* simplicity

**Comment by elioqoshi** [comment]
Thanks folks!

As we have some other pressing projects going on right now as well, we are able to provide some draft directions by next week and we can go from there :)

**Comment by huhn511** [comment]
No problem!. Just take your time @elioqoshi 

We have a new website in the pipeline, you can give us some feedback if you want and find the time.

You can find it here for the moment: [https://demo.nile.community/](https://demo.nile.community/)

We will publish it, after we found the logo together, let us know if you need anything else!

Thanks for your help! ❤️ 

Have a nice weekend!

**Comment by elioqoshi** [comment]
@huhn511 Great stuff! I'd however advise that the logo is not simply a mark to put on the left top corner, rather it should shape the whole branding experience. If you set the tone for the identity with the website, the logo loses a lot of power I'd say. Usually one expands from the logo into an identity, rather than derive the logo from a built identity. Just a thought.

@richardbmx would you like to help with this?

**Comment by huhn511** [comment]
@elioqoshi Cool, thanks for the nice input! Yes, that sounds right, we could place it for the planet on the website and just have a typographic "Nile" in the left top corner - or do you have other ideas?
We are open to your suggestions! 

Thanks, have a nice week.

**Comment by AnXh3L0** [comment]
Seems this has been completed, if there is anything else needed, please let us know.
