### ISSUE TITLE
Insignary - Design Layout of "Find a Distributor" page.

### ISSUE THREAD

**Issue by ergish** [uracreative/works#27]
This issue is about revising the  [Insignary](https://www.insignary.com/)'s Design Layout of [Find a Distributor](https://www.insignary.com/find-distributor) page and find a way to organize the information about the partners listed in the image below:
![partners](https://user-images.githubusercontent.com/44442505/53022585-c4cdca00-345b-11e9-875d-e14b95666d56.png)

A preview of the provided solution:
[Insignary - Find a Distributor - export.pdf](https://github.com/uracreative/works/files/2880429/Insignary.-.Find.a.Distributor.-.export.pdf)

The preview has been sent. The status is "waiting for a reply", so then @AnXh3L0 can apply the changes on the page.

**Comment by ergish** [comment]
@elioqoshi 
Please, can you add the right labels for this issue?

**Comment by elioqoshi** [comment]
Just did @ergish. Should be straightforward

**Comment by elioqoshi** [comment]
We should design another design layout grouped by continents instead of partners/resellers. For example, if I were to be a customer from America, I could quickly and easily identify which partner/reseller to reach out to.

Afterwards let's send both versions and let them decide what they prefer. @ergish Could you update that today?

**Comment by ergish** [comment]
@elioqoshi yes I am working with that.

**Comment by AnXh3L0** [comment]
The new layout has been implemented on their website yesterday.

**Comment by elioqoshi** [comment]
@AnXh3L0 @ergish please provide updates on the works here, not only in a sentence. Anyone outside Ura wouldn't be able to understand what was going on here.

I suppose the page is up on the staging website. It would be up soon here, right? https://www.insignary.com/find-distributor

**Comment by AnXh3L0** [comment]
Sorry about that, yes, the page is up at the link you provided above.
Below is a screenshot of the new layout.

![image](https://user-images.githubusercontent.com/25004151/53488570-fd3e5b00-3a8e-11e9-8820-c7813e92d9d1.png)
