### ISSUE TITLE
Oxidize New Website Implementation in Jekyll

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#28]
We will be implementing the redesign of the Oxidize website based on the new landing page we already designed and created the CSS for. This should be ready ideally next week.

Current Website: https://oxidizeconf.com/

Related to this: https://github.com/uracreative/works/issues/17

**Comment by elioqoshi** [comment]
@AnXh3L0 could you link to the landing page CSS here again please?

**Comment by elioqoshi** [comment]
Nevermind, CSS here

[Oxidize.zip](https://github.com/uracreative/works/files/2937744/Oxidize.zip)

**Comment by AnXh3L0** [comment]
The Oxidize website is now implemented in Jekyll, it is online here: https://oxidizeconf.com

![image](https://user-images.githubusercontent.com/25004151/55108383-c8e0ad80-50d3-11e9-863b-f4ea8fe220f1.png)

**Comment by elioqoshi** [comment]
Sounds good. Let's close this issue once the schedule and speaker photos are final.

**Comment by skade** [comment]
@elioqoshi we can also close this one :).

**Comment by elioqoshi** [comment]
@skade Thanks! 

For reference: https://oxidizeconf.com

Repo with the source code will be soon available.
