### ISSUE TITLE
Remmina Logo and Icons Redesign

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#3]
From the Open Source Design job board:
https://github.com/opensourcedesign/jobs/pull/304#issuecomment-375362119

**Comment by antenore** [comment]
This is not to push nor to stress, we are preparing a new release and we were wondering if we will have something to work on before that moment or not.

Really no stress at all, just curious.

Thanks!

**Comment by elioqoshi** [comment]
Thanks for the ping @antenore this slipped a bit behind. You will have a few logo proposals by Sunday :)

**Comment by antenore** [comment]
No rush! Thanks for the reply

**Comment by antenore** [comment]
They're really good, but we'd would prefer logo letter working on the original R, or around that theme.

**Comment by elioqoshi** [comment]
Why didn't you specify that before? You said that you'd be open to a redesign. If this was clear in the beginning we wouldn't need to go back and forth.

**Comment by elioqoshi** [comment]
What about these?

![image](https://user-images.githubusercontent.com/5436686/38454743-e9f441b8-3a6c-11e8-9b16-e75f41058c6c.png)

**Comment by antenore** [comment]
Sorry for this. Let me see with the other members, I'm not alone. Personally I prefer the second one.
I'm fine with a redesign, but the first attempt wasn't inspiring me.

**Comment by antenore** [comment]
Would it be possible to have the second green and blue in SVG so that we can try to replace the original one here: 

https://github.com/FreeRDP/Remmina/blob/next/remmina/desktop/scalable/apps/remmina.svg 

Without seeing it in action we are not able to "imagine" it 

cc @ic3d @giox069

**Comment by elioqoshi** [comment]
A logo needs to look good and get the message across on more mediums than the website, but that's how it would be currently:

![image](https://user-images.githubusercontent.com/5436686/38501159-9c5d34cc-3c0c-11e8-9ee6-3bdd05e7def0.png)

**Comment by elioqoshi** [comment]
SVG here:
https://demo.identihub.co/project/remmina

**Comment by antenore** [comment]
Thanks.

Well, as we are speaking about a desktop application, it matters really a lot for us to see it where is more used.

![image](https://user-images.githubusercontent.com/5975/38504616-6ba25fb6-3c15-11e8-8eec-f2734dbb4317.png)

Personally I like it, but I wait for the comments of my mates.

**Comment by antenore** [comment]
They both confirm for this one I've tested :-) 
Looks really nice

**Comment by elioqoshi** [comment]
Let me know if you want to go ahead with that. :)

**Comment by antenore** [comment]
Yes absolutely.

We are that kind of people that have an hard time to become habit to the changes, but now we have passed that initial obstacle, and we love it, you can go ahead.

Thank you.

**Comment by elioqoshi** [comment]
Solid! Will export the logo for you then. Continuing on the icons next.

**Comment by elioqoshi** [comment]
@AnXh3L0 can you push them to the repo?

**Comment by AnXh3L0** [comment]
Sure, they are now online at the repo, [here](https://github.com/uracreative/works/tree/master/Remmina).

**Comment by elioqoshi** [comment]
@antenore are you happy with the logo? Is that wrapped up?

**Comment by antenore** [comment]
@elioqoshi yes I'm happy thank you, but it's not yet in the source code because I want to do everything in one shot with the icons.

CC @giox069

**Comment by antenore** [comment]
@elioqoshi I'll be far few days, so I won't answer till Monday or Tuesday.

Before to expose the new logo we really want to have   the icon as well.

So we will wait you.

Soon there will be a new release, if you think you can do it we can wait.

Than we should also discuss about the cost. Can you contact me by email? My nickname At simbiosi.org

**Comment by elioqoshi** [comment]
I will continue with the icons and get back, sounds good

**Comment by AnXh3L0** [comment]
Hello @antenore,
We have prepared the icons, check the image below
![icons_remmina](https://user-images.githubusercontent.com/25004151/40793979-2fc6d672-64fe-11e8-9d75-147770c092a8.jpg)

**Comment by elioqoshi** [comment]
Feedback appreciated. Please note that the icons are color independent so that depends on the UI where they will be

**Comment by antenore** [comment]
Thanks! We're discussing between us.
I'll be back as soon as possible

**Comment by elioqoshi** [comment]
Sure. We are making small tweaks to the icons so a general feeling would be enough to see if we can move on :)

**Comment by antenore** [comment]
In general we like it, but we really need the icons so that we try on the UI.

Personally I'd prefere a different icon for the rdp protocol, we don't want it looks like the Remmina logo. It should remember somehow the Microsoft logo.

For the budget it s in my original request but I prefer we discuss this privately.

**Comment by antenore** [comment]
My email is my name @simbiosi.org

**Comment by elioqoshi** [comment]
@antenore Makes sense

Although the icons should be color agnostic and they can be dynamically changed in the UI I hope.

@AnXh3L0 can you do necessary changes?

**Comment by antenore** [comment]
@elioqoshi @AnXh3L0 just change the shape. No colours is fine.
Thanks

**Comment by antenore** [comment]
Even an 'M$' what do you think? :-D

**Comment by AnXh3L0** [comment]
I have made the changes you suggested @antenore and added the icons as svg in the zip below so you can test them in the UI.
[Icons_Remmina.zip](https://github.com/uracreative/works/files/2064821/Icons_Remmina.zip)

**Comment by antenore** [comment]
Thanks! Today I'm not sure I'll be able to take a look, I'm out the whole day.
I'll let you know. Thanks!

**Comment by antenore** [comment]
Really gorgeous :-)

**Comment by antenore** [comment]
@AnXh3L0 
How am I supposed to use this SVG? Sorry but I'm far to be even a n00b in these stuff.
I hope I don't have to cut&paste each icon in a new file!?!?

**Comment by AnXh3L0** [comment]
Hi @antenore,

Sorry about that, here are all the icons separated as SVG for you ready to use.
[icons.zip](https://github.com/uracreative/works/files/2065411/icons.zip)

**Comment by antenore** [comment]
Thank you @AnXh3L0 !

**Comment by antenore** [comment]
So here we are...

First of all, good job!!

![new_icons_default_theme](https://user-images.githubusercontent.com/5975/40881600-2b8bad48-66cb-11e8-9b31-2c42ad6a824f.png)
![new_icons_high_contrast_theme](https://user-images.githubusercontent.com/5975/40881601-2ba99d9e-66cb-11e8-8ceb-48c0c5a8050f.png)

These are 2 tests with a quite default icons theme and one with an high contrast one.
Personally I like, I'm just worried regarding the stock icons we use, for example, the tools/gear icons, the keyboard icons. I think, but I'm not sure, I will have to work with CSS, to make all the icons/colours looks "darkish". If you are aware of any tricks, please let me know.

The spice icon doesn't look so good because I've converted it to 16x16 and 22x22 px. Is it possible to modify the original vector one so that it takes more vertical space (to have a square at end)? Maybe giving a bit of prospective?

I'd like also the feedback of @giox069 , @ic3d and the other most active Remmina contributors (if the want)

cc @larchunix @amtlib-dot-dll @3v1n0 @mfvescovi

**Comment by elioqoshi** [comment]
Thanks @antenore!
I suppose it would be best if all icons are in the same style. @AnXh3L0 can you ensure to put all icons into square boundaries so the margins are consistent across them? They are currently not in the screenshot

**Comment by AnXh3L0** [comment]
Can you try the new ones below? I made them square so they should all look consistent.
[icons square.zip](https://github.com/uracreative/works/files/2065827/icons.square.zip)

**Comment by antenore** [comment]
Thanks @AnXh3L0 I'll have a look tomorrow.

**Comment by antenore** [comment]
Size are good now :-) thanks.
One more request, can you also add "spice over ssh"? 
Than I really need some days so that everybody will have the time to test and let us know what they think.

@elioqoshi don't forget to contact me by email. ;-)

**Comment by elioqoshi** [comment]
@antenore @AnXh3L0 reached out to you via email already

**Comment by antenore** [comment]
@elioqoshi @AnXh3L0 it's strange I didn't get any email I took a look also on the server there is nothing filtered. let's try @gmail.com could be some blacklist on my or on your side.

**Comment by AnXh3L0** [comment]
Hi @antenore,

I resent the email to you at gmail. Below you have the spice over ssh icon.
[spice over ssh icon.zip](https://github.com/uracreative/works/files/2068208/spice.over.ssh.icon.zip)

**Comment by antenore** [comment]
@elioqoshi @AnXh3L0 I'm going to update the remmina_about.glade to add your names as contributor, what do you want I write as you mail?

https://github.com/FreeRDP/Remmina/blob/master/data/ui/remmina_about.glade#L158

**Comment by AnXh3L0** [comment]
Hey @antenore, you can add my email as anxhelo @ lushka dot al. Thanks!

**Comment by elioqoshi** [comment]
@antenore we would prefer to credit Ura Design in general as we think a collective of people is a stronger concept than any individual :) A credit is not required though, all the rights to the works are yours (we have to clarify the licensing from the icons which are Material Design based though)

**Comment by antenore** [comment]
I'll add it.

For the license let me know.

Thanks

**Comment by antenore** [comment]
Hi all. Sorry to come back regarding the icons, but have a little problem.

I've switched the way I use the icons, setting them as symbolic icons. 
This is to allow the Gnome/Gtk+ theme engine to adapt the colors based on the active theme.

With the toolbar icons everything works perfectly, but with the protocol icons not.

These are the rendered protocol icons and as you can see the RDP one is just a round circle.

![image](https://user-images.githubusercontent.com/5975/41176553-28f07ea2-6b61-11e8-8bd5-a2aa8db2fe54.png)

Have a look also on the other protocols icons (to me they looks good) if you think anything is missing compared to the original.

The toolbar icons are perfect!

![image](https://user-images.githubusercontent.com/5975/41176623-6f6fb6c2-6b61-11e8-8622-f23f4de4f0a1.png)

Again with a dark theme

![image](https://user-images.githubusercontent.com/5975/41176998-bc3db016-6b62-11e8-88f5-dbdcd9db3449.png)

![image](https://user-images.githubusercontent.com/5975/41177031-d5711f6e-6b62-11e8-93bd-550f7becf12e.png)

I'm trying to fix it by myself but I'm afraid I'm not very competent :-P

**Comment by antenore** [comment]
Ah! I've got it!

I'm uploading the updated file.

**Comment by antenore** [comment]
[remmina-rdp.zip](https://github.com/uracreative/works/files/2085861/remmina-rdp.zip)

The four squares where placed above a full/filled circle (and lock in the second one).

So I've reduced the alpha of the squares till 0, selected all the path and executed a difference, to have only one shape with the transparent squares.

[This](https://graphicdesign.stackexchange.com/questions/20196/using-the-shape-of-an-object-to-cut-the-object-beneath-it-in-inkscape#42590)
