### ISSUE TITLE
TeleIRC Logo

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#30]
https://github.com/RITlug/tasks/issues/116

We are creating a logo and some basic branding for TeleIRC, RITLUG's Telegram and IRC bridge tool.

**Comment by richardbmx** [comment]
@elioqoshi  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by elioqoshi** [comment]
@richardbmx Hi! Great to see some interest in this :)
Would love to have some additional ideas for this project. Basically it's a small tool which makes it easier to configure communication bridges between Telegram and IRC.

**Comment by jwflory** [comment]
Hi! I thought I would add some context and design motivation for our project here.

Teleirc is an open source project to connect IRC channels with Telegram groups. Our project is part of the [RIT Linux Users Group](https://ritlug.com/) (RITlug). Ura [previously created](https://github.com/uracreative/works/blob/b04609e391f983e2fc74fa0ad79ae9a4bef22f9a/RitLUG/SVG/vertical_color_with_wordmark.svg) the logo for RITlug and having some unity to that
design helps connect our project back to RITlug.

The easiest way to visualize Teleirc is a connector of two different worlds (IRC and Telegram). While other bridge projects focus on offering several integrations, Teleirc focuses on being lightweight and lean. We do one thing and we aim to do it well. Being simple and straightforward is also part of our project's identity and we hope to convey that in a graphic design.

**Comment by richardbmx** [comment]
Perfect I'm going to work on some ideas to present

**Comment by richardbmx** [comment]
I have related this idea which expresses the bridge between both app, with the symbol of Telegram giving the impression that jumps between both words, it is a simple clean design that adapts easily in any size or background color. I hope you like it if you want some change you just have to ask for it and I will do it.

![logo130](https://user-images.githubusercontent.com/35604837/55733654-305bfe80-59ec-11e9-9fb1-e846273ac3a6.png)

**Comment by elioqoshi** [comment]
@richardbmx Thanks for the proposal! I like where this is going :)

I have a few concerns though: the paperplane icon is too small to be recognized and I'm not sure if it's readable as TeleIRC. This might pose problems while keeping the bridge visual (I tried it myself and struggled too). I'd like @jwflory7 to chime in on this though as well :)

**Comment by elioqoshi** [comment]
Here are 2 proposals from my side:

![image](https://user-images.githubusercontent.com/5436686/55782469-a58f0880-5aac-11e9-8ac2-c3f3e6a0fb9a.png)

What do you think?  the font type used is Inter which is an open font.

**Comment by jwflory** [comment]
Hi all, I liked all of the drafts so far. I do agree with @elioqoshi that the first draft is difficult to read though. I liked @elioqoshi's bottom option with the paper airplane.

**Comment by elioqoshi** [comment]
@jwflory Thanks for the feedback! Do you want to go ahead with that option then?

**Comment by elioqoshi** [comment]
@jwflory like this: 
![image](https://user-images.githubusercontent.com/5436686/55864764-654b8b00-5b7d-11e9-94d1-a3f02cd4229e.png)

**Comment by jwflory** [comment]
I love this! :heart_eyes: I'll ask some of the other developers to weigh in with feedback, but I think this is what we are looking for.

**Comment by Tjzabel** [comment]
I love this as well! @elioqoshi would you also be able to do a second image/logo with just the blue emblem on the left without the words? It would be helpful to have both options available.

**Comment by elioqoshi** [comment]
@Tjzabel sure, that's the default approach anyway, together with a vertical version as well. @AnXh3L0 could you help push these final files to our repo?

**Comment by AnXh3L0** [comment]
Sure, will push them to our repo asap.

**Comment by AnXh3L0** [comment]
@jwflory @Tjzabel Below you can find the assets, uploaded on our repo.

https://github.com/uracreative/works/tree/master/TeleIRC

**Comment by Tjzabel** [comment]
@AnXh3L0 @elioqoshi thanks so much!! :tada: :tada:

**Comment by jwflory** [comment]
This is fantastic, thanks so much everyone for your help on the logo! :tada: :tada:

**Comment by elioqoshi** [comment]
Thanks folks! It would be appreciated if you can support Open Source Design on Open Collective :)
https://opencollective.com/opensourcedesign

And for the brochure, feel free to open up a request on the Jobs board:
https://opensourcedesign.net/jobs/
