### ISSUE TITLE
Software Freedom Podcast Logo

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#34]
The FSFE asked us to create a logo/artwork for their upcoming Software Freedom Podcast.

A few remarks:

> * The logo should be in accordance with the guidelines for iTunes/etc.
> podcast logos
> * The name of the project is "Software Freedom Podcast"
> * The name should be on the logo
> * It would be nice to have some colour / symbolic reverence to the
> fsfe´s logo (similar colours or the stars from the logo...)

**Comment by elioqoshi** [comment]
This is a draft proposal of mine:
![image](https://user-images.githubusercontent.com/5436686/64603795-37cf6b80-d3c1-11e9-82ff-2029a2274617.png)

**Comment by ergish** [comment]
This is another version from me.
Considering the fact that we are dealing with a podcast series, I think an artwork would work better than an icon logo in the podcast lists.
The format is a 1x1 rectangle but considering the content, it can be easily adapted in any other format.

![FSFE Free Software Podcast - Logo-04](https://user-images.githubusercontent.com/44442505/64910355-af7cfd80-d715-11e9-9cf4-75725747c2e3.png)

But of course, the graphic elements can be used even as a logo for the Free Software Podcast, just like the versions below.

![FSFE Free Software Podcast - Logo-05](https://user-images.githubusercontent.com/44442505/64910460-14852300-d717-11e9-95fa-d50e63b19507.png)

**Comment by ergish** [comment]
So here's another proposal. Considering the fact that we are dealing with a podcast series, I think it will need an art cover for its appearance in any podcast list.
![SOFTWARE FREEDOM PODCAST-01](https://user-images.githubusercontent.com/44442505/64911714-954b1b80-d725-11e9-9526-7b628fc03edb.png)

In any case, the graphic elements are also adjusted in these compositions, horizontal and vertical, which can be used as a logo for Software Freedom Podcast.

![SOFTWARE FREEDOM PODCAST-02](https://user-images.githubusercontent.com/44442505/64911815-d42da100-d726-11e9-8922-23ad7168178f.png)
![SOFTWARE FREEDOM PODCAST-03](https://user-images.githubusercontent.com/44442505/64911818-d42da100-d726-11e9-9551-1be2cab57ca9.png)

**Comment by ergish** [comment]
After the feedback here's a merged output keeping the nature of the colors from the first draft and the graphic elements of the second proposal.
![Software Freedom Podcast - Artwork-07](https://user-images.githubusercontent.com/44442505/65834934-85643780-e2e0-11e9-8d39-f19186aa44d1.jpg)

**Comment by elioqoshi** [comment]
@ergish Is there a final decision on this yet?

**Comment by IfeanyiEkperi** [comment]
My submission for the logo.

![20191018_100819](https://user-images.githubusercontent.com/6451526/67081736-a2798100-f18f-11e9-8b22-6892b06d9d52.jpg)

**Comment by elioqoshi** [comment]
@IfeanyiEkperi Hi! Thanks for your contribution here! Unfortunately we already submitted a proposal which was chosen. Would you like to be involved in future projects however? Happy to chat.

**Comment by IfeanyiEkperi** [comment]
Sure @elioqoshi. I really want to be involved more in helping Open Source with my skill.

A little guide would help

**Comment by elioqoshi** [comment]
This is wrapped up, thanks :)

@IfeanyiEkperi if you like we can talk more on https://discourse.opensourcedesign.net !
