### ISSUE TITLE
Digital Security Guideline for HRCo - Guideline Book Design

### ISSUE THREAD

**Issue by ergish** [uracreative/works#35]
The Design of the Digital Security Guideline for HRCo consists of creating a clean, consistent, aesthetic look for the guideline book and it's readers, providing the entire book design, illustrating and graphically organizing its content in three languages: "English", "Afaan Oromoo" and"Amharic"

**Comment by IfeanyiEkperi** [comment]
I wish to apply to work on this issue

**Comment by elioqoshi** [comment]
@IfeanyiEkperi Hey, thanks for the interest, however this is a design task with a tight deadline so we are doing this internally. The process will be covered here however.

**Comment by elioqoshi** [comment]
This has been published here:
https://www.localizationlab.org/blog/2020/2/4/digital-security-guideline-for-human-rights-defenders-and-journalists-in-ethiopia
