### ISSUE TITLE
Thunderbird OTR Chat Usability Audit

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#37]
Thunderbird is currently testing a new feature call OTR (Off-the-record) chat. Thunderbird has millions of users worldwide, even in places where there is a great deal of government surveillance and suppression of free speech. OTR chat will allow a great deal of people to have encrypted conversations with one another using an open standard within auditable open source software.

As part of the OTF Usability Lab, we should scope accordingly to help Thunderbird with some testing and usability auditing of their upcoming OTR Chat features.

**Comment by elioqoshi** [comment]
This has been approved by OTF so we can go ahead with it. @RenataGegaj can you specify a timeline of this work?

**Comment by RenataGegaj** [comment]
We plan to conduct three remote usability testing sessions with six users in total. The testing will be with participants in pairs, where they will connect and exchange messages using Off The Record(OTR) encryption on Thunderbird client(beta version). 
We have already started with participant recruiting and expect to conduct the sessions very soon. 
You can find the testing guide and all the details here: https://www.notion.so/Thunderbird-OTR-Usability-Audit-Guide-e308d07e1a93419ab2e8941130f745b2

Deliverables: A report on a written format or presentation with test findings and recommendations

**Comment by elioqoshi** [comment]
The report can be found in the interim on Google Docs:
https://docs.google.com/document/d/1pzCUAdezvzG_86lid9xL2k2JODGyV9eERMo98qfuD-A/edit?ts=5e42a588#heading=h.3ps1rnhhqbqb

After proofreading it we plan to publish it on our website in the coming week.

**Comment by RenataGegaj** [comment]
This is the final version of the report, in pdf format: [Usability testing report for Thunderbird Chat and OTR encryption.pdf](https://github.com/uracreative/works/files/4853304/Usability.testing.report.for.Thunderbird.Chat.and.OTR.encryption.pdf)
