### ISSUE TITLE
Global Leaks Website Redesign

### ISSUE THREAD

**Issue by RenataGegaj** [uracreative/works#38]
On continuing efforts to improve its user experience, we are working on redesigning Global Leaks website.  This is a brief summary of what we will be working on
 
### Research Phase
**Usability Evaluation:** We will start the project by evaluating the usability for the current site to help us identify user journey pain points and have them as reference points for future improvements

**Information architecture:** Will continue with tackling the Information infrastructure for the current site. We will perform various IA exercises to help us decide what needs to be rearranged and how
 
**Sitemap development:** Combining the results extracted from previous Information architecture work with the sitemap proposal from Global Leaks team, we will lay the foundations for the new webpage with a sitemap which will describe the basic structure of the site organization and hierarchy

**Content:** Next, in collaboration with the Global Leaks team we will start working on the content. We'll help review the content and adjust if needed

### Design & Development Phase 
 
- Visually implement all findings from the research phase and lastly make them fully functional. We will use Bootstrap to do this. 

We'll be in sync with Global Leaks team throughout all phases and iterations, making sure we incorporate their requirements and additional features

**Comment by AnXh3L0** [comment]
Inner pages have been filled with draft content provided by the GlobaLeaks team and graphics/illustrations are being worked on to be included in all pages.

**Comment by AnXh3L0** [comment]
After the creation of the GlobaLeaks branding guidelines, those guidelines (and changes revolving them) are being implemented in the site. During the weekend accessibility testing will be made and by Monday we should we ready to wrap the project if there is no more feedback from the GlobaLeaks team.

**Comment by elioqoshi** [comment]
The new website is here btw:
https://newsite.globaleaks.org/

**Comment by RenataGegaj** [comment]
I did a quick review of the site, it looks great 🎉I really like the design and the simplicity, I think it pairs well with GL overall branding. I'm leaving some suggestions here that I think would improve the user experience of the site. 
 
<img width="731" alt="Screenshot 2020-04-17 at 12 20 48" src="https://user-images.githubusercontent.com/7413721/79595040-74451180-80de-11ea-921b-41f5924c395d.png">

The "Try" and "Learn more" buttons are not consistent. One of them looks like a button and the other looks like a link. The heart icon inside the "Try" button and the color of it, give a first impression that it is a "Donate" button and it will redirect to a donate page instead on a "Demo" page.
Also the open positions option I think would fit more in the footer instead of "About us" on the navbar.

<img width="116" alt="Screenshot 2020-04-17 at 12 21 50" src="https://user-images.githubusercontent.com/7413721/79595121-99398480-80de-11ea-9833-380e7aed6ede.png">


It would be good to have Global Leaks logo as a favicon here.

<img width="1281" alt="Screenshot 2020-04-17 at 12 22 47" src="https://user-images.githubusercontent.com/7413721/79595223-bc643400-80de-11ea-9ef3-26ba847c2492.png">

"Global Leaks Features" section on the homepage and the "Features" option on the navbar contain the same information. I think the "Features" option in the navbar is redundant and can be replaced with some information that needs to be frequently accessed by users or maybe even get rid of it and don't replace it with anything, for more simplicity.

<img width="1281" alt="Screenshot 2020-04-17 at 12 27 15" src="https://user-images.githubusercontent.com/7413721/79595261-d30a8b00-80de-11ea-92e6-de6b5f2fe0ca.png">


The slider can be moved on two places, either by the numbers or the arrows. I think keeping just one of these will help to avoid confusion.


There are some small issues with accessibility in the button names, color contrast and labels that can be easily fixed. I used this tool to do the automated testings: https://accessibilityinsights.io/
It also gives you detailed suggestions on how to fix the issues.
<img width="1371" alt="Screenshot 2020-04-17 at 12 37 50" src="https://user-images.githubusercontent.com/7413721/79582650-5373c080-80cc-11ea-9dc5-424915818985.png">


<img width="1371" alt="Screenshot 2020-04-17 at 12 38 54" src="https://user-images.githubusercontent.com/7413721/79582654-540c5700-80cc-11ea-9cf3-410e826f5242.png">

I also did a manual test for keyboard focus, using voice over utility. The problem i found is that the sub pages are unreachable by the keyboard.  

<img width="1418" alt="Screenshot 2020-04-17 at 18 57 00" src="https://user-images.githubusercontent.com/7413721/79594990-5d9eba80-80de-11ea-8d29-766541bbbe6c.png">

**Comment by AnXh3L0** [comment]
Thank you Renata, your points have been addressed :)

**Comment by elioqoshi** [comment]
@AnXh3L0 @RenataGegaj Thanks!

I have some style comments on the landing page which I handily exported to Pastel where I added comments for easier viewing.


https://usepastel.com/link/7q5e0/

**Comment by AnXh3L0** [comment]
The GlobaLeaks team had some feedback and those were implemented/fixed in the latest version of the website. This is ready to be wrapped up.

**Comment by AnXh3L0** [comment]
The GlobaLeaks is in need of a few more illustrations to wrap up this work.

**Comment by elioqoshi** [comment]
[GlobaLeaks Brand Guidelines v3.0.pdf](https://github.com/uracreative/works/files/4605814/GlobaLeaks.Brand.Guidelines.v3.0.pdf)

Also updated the Brand Guidelines. Changes should have been implemented and our part of the work is completed here. Closing this issue.

**Comment by evilaliv3** [comment]
Thank you @elioqoshi for all the corrections on the brand guidelines, it seems all great.

Actually as for the website were reported some defects still to be corrected; hoping to help i've annotated them here. If you agree now that the site is pretty finalized i may try to fix them myself to start getting the know how on the website that will be necessary for further maintenance. I will eventually ask @AnXh3L0 some advice on which are the files that contains the changes with respect to the original template used.

- the copyleft character appear still not visible; we suggest the possiblity to use the a CSS style for reversing the CC icon from fontawesome

- some of the colors uses inside the website seems to be inconsistant; in particular please check the following two situations:

1) shouldnt the following background be #103253 (blue zodiac)? as well the colors of the logo here seems incorrect.
![Screenshot_2020-05-10 Home](https://user-images.githubusercontent.com/217034/81511429-c19d5300-9319-11ea-86ee-fbddb7210849.png)

2) shouldnt this background be #3777BC (mariner blue)?
![Screenshot_2020-05-10 Home(1)](https://user-images.githubusercontent.com/217034/81512388-8ce0ca00-9320-11ea-84d0-13db74b96686.png)

**Comment by elioqoshi** [comment]
@evilaliv3 You are right with these points. I see you already implemented these changes yourself, right?

**Comment by evilaliv3** [comment]
They have been applied by @AnXh3L0. Its all great! Thank you
