### ISSUE TITLE
I2P Console & Home Redesign: Identity and Values Workshop

### ISSUE THREAD

**Issue by RenataGegaj** [uracreative/works#39]
Continuing on the foundations of the tone of voice in 2018’s I2P style guide, we will conduct a workshop to further layout these values and drive consensus throughout the I2P project on the vision of the project and how it represents itself. These learnings will provide a set of values we will utilize during the later Rebranding phase.

Deliverables:		
Document outlining a set of principles and values I2P represents

**Comment by elioqoshi** [comment]
Changed the effort as it took longer than 10 hours.

**Comment by RenataGegaj** [comment]
We conducted the Identity&branding workshop and also created a complementary exercise/survey to go with it as we aimed to involve the community in this process.
We covered mission statement, tone of voice, personality also some style tips.
The next step is is to create a unique design and well-defined graphics that visually “speak” the same language as the brand and have the same personality traits.
You can find the complete work here: [I2P - Brand and Identity Brief.pdf](https://github.com/uracreative/works/files/4444081/I2P.-.Brand.and.Identity.Brief.pdf)

**Comment by RenataGegaj** [comment]
We did a few adjustments on WHY, HOW, WHAT statements, together with the I2P team. We are now reviewing and finalizing our work.

**Comment by RenataGegaj** [comment]
We refined  WHY, HOW, WHAT statements, and went through tone of voice and personality once more, to make sure it all ties in well. You can find everything related to I2P Identity on the attachment below, we will also include it on the I2P style guide very soon.
[I2P - Brand and Identity Brief - V2.pdf](https://github.com/uracreative/works/files/4914640/I2P.-.Brand.and.Identity.Brief.-.V2.pdf)
