### ISSUE TITLE
Open Humans Logo and Visual Identity 

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#4]
We are working on the new Visual Identity for Open Humans:
http://openhumans.org/

Currently proposals are up on Identihub (updated from time to time)
https://demo.identihub.co/project/openhumans

We are currently doing feedback rounds to decide on a logo. Will update once there is progress.

**Comment by elioqoshi** [comment]
This has been wrapped up. @AnXh3L0 could you please add the final logo files to the repo here?

Assets on our Identihub Test instance:
https://test.identihub.co/project/open-humans

**Comment by elioqoshi** [comment]
@madprime there you go! Closing this. For anything else feel free to ping us. :)

**Comment by elioqoshi** [comment]
@AnXh3L0 can you create an Identihub page with all these assets please as well? Let me know if there is any design aspect missing.

**Comment by AnXh3L0** [comment]
@elioqoshi here is the Identihub Project page for Open Humans: https://demo.identihub.co/open-humans#/

**Comment by elioqoshi** [comment]
This is finished, thanks!
