### ISSUE TITLE
I2P Console & Home Redesign: Information Architecture Sprint

### ISSUE THREAD

**Issue by RenataGegaj** [uracreative/works#41]
With the help of Ura’s I2P Usability Study in 2018, and a dedicated two-day sprint, we will redesign the information architecture of the I2P console. A set of design principles and personas will be required as a prerequisite for this activity.

Deliverables:		
Console Information Architecture recommendations
Website Information Architecture recommendations
Lead: Simply Secure

**Comment by georgiamoon** [comment]
@RenataGegaj can we add @bumbleblue here too?

**Comment by RenataGegaj** [comment]
We completed a two-day Information Architecture sprint. We redesigned the information architecture for I2P console and I2P website, also offered recommendations for improvements, some of them we are currently implementing on the console redesign.

Thank you Simply Secure for leading this phase and @bumbleblue for organizing awesome workshops!

@bumbleblue Is there any outcome from the workshops that's possible to attach here?

**Comment by elioqoshi** [comment]
@bumbleblue can you share the outcomes here for future reference? I suppose this issue is good to be closed afterwards?

**Comment by RenataGegaj** [comment]
@bumbleblue has already done a writeup on outcomes from the workshop. If you have anything you'd like to attach here pls let me know.

I'm closing this issue for now

**Comment by bumbleblue** [comment]
[[I2P] IA Workshop All Boards.pdf](https://github.com/uracreative/works/files/4682928/I2P.IA.Workshop.All.Boards.pdf)
Here are all screen from the two workshops. I will also post the write-up when it's published! Thanks.
