### ISSUE TITLE
I2P Console & Home Redesign: Branding Foundations Update

### ISSUE THREAD

**Issue by RenataGegaj** [uracreative/works#42]
With the learnings from Phase 3, we will start drafting proposals to incorporate the identity values outlined as a new brand. We will take into account the potentially problematic brand recognition of the project and come up with proposals to address these concerns. This work will include meetings with the I2P core team and various revisions throughout the design stage.

Deliverables:		
New Brand Foundations (Logo, Colors, Typography, Iconography)
Style Guide Update with new Brand Foundations

**Comment by ergish** [comment]
After defining the Personality and the Voice of I2P we are proposing 5 directions for the new Brand and Visual Identity of I2P.

The files below contain:
1. Logo
2. Logo Alternations
3. Color Palette
4. Typography
5. Pattern as a composition of the visual components of the identity.

[I2P - Brand and Visual Identity - Proposal 1.pdf](https://github.com/uracreative/works/files/4470198/I2P.-.Brand.and.Visual.Identity.-.Proposal.1.pdf)
[I2P - Brand and Visual Identity - Proposal 2.pdf](https://github.com/uracreative/works/files/4470201/I2P.-.Brand.and.Visual.Identity.-.Proposal.2.pdf)
[I2P - Brand and Visual Identity - Proposal 3.pdf](https://github.com/uracreative/works/files/4470205/I2P.-.Brand.and.Visual.Identity.-.Proposal.3.pdf)
[I2P - Brand and Visual Identity - Proposal 4.pdf](https://github.com/uracreative/works/files/4470206/I2P.-.Brand.and.Visual.Identity.-.Proposal.4.pdf)
[I2P - Brand and Visual Identity - Proposal 5.pdf](https://github.com/uracreative/works/files/4470197/I2P.-.Brand.and.Visual.Identity.-.Proposal.5.pdf)

**Comment by ergish** [comment]
The Brand and Visual Identity of I2P is decided and approved!

After getting feedback and discussing the symbols and colors that represent the I2P values and what makes it different, we have been working on one of the proposed brand directions (_previous comment_), finding the right balance in the brand colors to represent I2P personality and to be UI effective as well.

PDF Presentation:
[I2P - Brand and Identity - Presentation.pdf](https://github.com/uracreative/works/files/4551214/I2P.-.Brand.and.Identity.-.Presentation.pdf)

**Comment by AnXh3L0** [comment]
After the new I2P brand approval, the style guide website will now be updated. The current last version of the style guide resides at https://uracreative.github.io/i2p-styleguide

**Comment by AnXh3L0** [comment]
The style guide now includes a dark theme and has been updated with the I2P Brand and assets.

**Comment by elioqoshi** [comment]
Thanks @AnXh3L0.

Let's continue with this next week when the dust has settled a bit.

**Comment by AnXh3L0** [comment]
Agreed, will resume work next week.

**Comment by RenataGegaj** [comment]
We've continually done adjustments based on feedback, see the latest iteration of the I2P style guide here: https://uracreative.github.io/i2p-styleguide/brand/
