### ISSUE TITLE
Briar - User testing for transport toggles

### ISSUE THREAD

**Issue by RenataGegaj** [uracreative/works#45]
Will be conducting usability testing sessions for the following UI changes:

-   The bottom section of the navigation drawer, containing the Tor/wifi/Bluetooth icons, is now expandable
-   The expanded section contains switches for controlling whether Briar connects to contacts via Tor/wifi/Bluetooth
-   The settings for Tor and Bluetooth in the settings screen have been updated to reflect the existence of the new switches

**Comment by elioqoshi** [comment]
This should take less than 10 hours as the budget is for 1 day of testing.

**Comment by RenataGegaj** [comment]
I conducted three remote user testing sessions for the new UI of transport toggles.
The approach to testing this was interviewing combined with usability testing instead of only usability testing where I would give a few tasks to users and observe whether they can accomplish them or not. I decided to do this way of testing because it gives more context to why the user is having issues using the feature but also how this feature ties in with the overall user experience of Briar. 
You can find the full report here: https://code.briarproject.org/briar/briar/issues/1723
