### ISSUE TITLE
EmergenCITY Website Redesign & Development.

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#46]
We are redesigning and developing in Jekyll the website of Emergencity:
https://www.emergencity.de/

## Plan
- Milan and Matthias provide us an initial Sitemap. We will work with them to sync the wireframes based on the sitemap.
- We are reviewing the branding to make sure it offers enough flexibility for our needs. That includes logos, color palette and typography. We will provide some various proposals afterwards and apply the updated branding after approval.
- Next step is to create the mockups based on the sitemap wireframes and with the branding applied.
- After various feedback iterations on the design, once it is signed off we will continue with the implementation of the jekyll website based on the mockups specs in Figma.
- Potential bugs and issues on the website will be ironed out last.
- We should document how the website is set up and how content can be added and changed.

## Team

@rudolfburgaj will be building out the wireframes and design mockups
@AnXh3L0 will be implementing the jekyll website 
@elioqoshi will be taking on branding and manage the processes

## Timeline

We should aim to deliver the final website latest by end of June. More specific milestones coming soon here.

**Comment by elioqoshi** [comment]
*@elioqoshi attached a* [message](https://chat.ura.design/ura-design/pl/dqxnroytabfxpdunkemsggauoh) *from @elioqoshi*
@channel We have a first draft of the home page wireframes ready. You can see it here:
https://www.figma.com/file/9QfVOD2soeXrDkvf71jipU/EmergenCITY?node-id=0%3A1

You can create an account on Figma to leave comments on specific parts and we can discuss and address them. Once we went through 1 or 2 iterations to ensure the structure is what's needed, we will start to turn these into more complete designs.

Meanwhile I will be collecting your branding and logo elements to propose a few directions. @rudolf will work in the meantime on the wireframes for the remaining inner pages.

**Comment by elioqoshi** [comment]
*@elioqoshi attached a* [message](https://chat.ura.design/ura-design/pl/oznc3ho5kbn9jgcdo7juxgggzc) *from @elioqoshi*
The first iterations of the logos can be found here: https://www.figma.com/file/9QfVOD2soeXrDkvf71jipU/EmergenCITY?node-id=21%3A12

There are 2 proposals, each with a few variations. Proposal 1 tries tro keep the current logo similarities as much as possible. I'd say this doesn't work out very well though since the great amount of lines looks not great on small resolutions. The great amount of color also might not be beneficial to recognize the logo. Proposal 2 builds up on these issues and works with nodes instead of circles and uses simplified shapes. This works better for smaller resolutions and a variety of mediums.

Proposal 2C is what I'd suggest to go ahead with, as we can build better on the green color palette across the website then.

Feel free to comment on Figma with your comments.

**Comment by AnXh3L0** [comment]
The EmergenCITY website has now been completed and it will be live soon at the link https://emergencity.de. A screenshot of the homepage is below.
![image](https://user-images.githubusercontent.com/25004151/93874590-df20f700-fcd3-11ea-83c6-7ab3445f3f14.png)
