### ISSUE TITLE
GIZ & openIMIS - Assets

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#48]
We are working with GIZ and openIMIS to create a design library for all communication and design assets in open file formats and licenses.

## About openIMIS:
https://openimis.org/

Health financing schemes require the highly efficient implementation of multiple and complex business processes.

Scheme operators in low- and middle-income countries struggle to achieve efficiencies in these schemes when they lack access to appropriate digital technologies. openIMIS is an open-source software which helps manage these processes.

## Deliverables

We are currently working to have the existing assets converted into versatile open file formats. The current assents can be found here:
https://openimis.atlassian.net/wiki/spaces/OP/pages/942473232/Communication+Materials

Our Google Doc tracks the progress on the various files:
https://docs.google.com/spreadsheets/d/1mwC1nbGxa5_iCEhSOotx1fCQmAjRs2bsqG2IcYTTFq8/edit?usp=sharing

Currently the openIMIS logo uses a proprietary font so we need to update the brand guidelines with an openly licensed font alternative and update the deliverables accordingly.

## Timeline & Plan

**5 June** - Logo updated with new font. All assets converted. Download as a zip file available.
**11 June** - Sync Call with openIMIS Team
**12 June** - Create new Wiki page and structure for all new assets and document accordingly. Reviewing and feedback for assets open.
**26 June** - Feedback for assets closed.
**3 July** - Feedback and changes addressed and updated.

**Comment by elioqoshi** [comment]
now there is a central page for the openIMIS assets, it is found here: https://openimis.atlassian.net/wiki/spaces/OP/pages/1490649147/Design+Communication+Assets

You might notice that some files are missing

that's because, in my opinion, there needs to be a unification (of things such as icons used in presentations/graphics) before adding them to this central page

**Comment by AnXh3L0** [comment]
After the last call with GIZ, the new assets page has been implemented and available at the same link as above, https://openimis.atlassian.net/wiki/spaces/OP/pages/1490649147/Design+Communication+Assets. 

This page now contains an overview of all the current assets openIMIS uses and serve as a basis for creating new content in the future. This part of the project has been finished.
