### ISSUE TITLE
Cotech Hugo Website Implementation

### ISSUE THREAD

**Issue by AnXh3L0** [uracreative/works#49]
We are implementing the Cotech website in Hugo according to their mockups.
[cotech.de](https://cotech.de)

## Plan
- Mockups were provided beforehand, along with some of the assets.
- We start working on implementing the website using the Hugo static site generator.
- Next step is a feedback session in 2 weeks to finalize the website.

## Team
@AnXh3L0 will be implementing the website in Hugo.

## Timeline
Final delivery is end of June 2020.

**Comment by elioqoshi** [comment]
@AnXh3L0 can you update us on this please?

**Comment by AnXh3L0** [comment]
The 2nd round of feedback and iterations has been completed this Friday and content is being added as we speak by the Cotech team. The current live preview of the site can be explored at this link https://epic-engelbart-5e7acf.netlify.app/.

Work can be considered done and issue closed.
