### ISSUE TITLE
GlobaLeaks Website Illustrations

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#52]
We worked with Mathew Wong (https://hyperfolk.design ) on the new set of GlobaLeaks illustrations as part of the new GlobaLeaks website relaunch. OTF is supporting this work and also including these in the brand guidelines for further usage. The illustrations can be seen here:

![GL Illustrations](https://user-images.githubusercontent.com/5436686/87679209-2fcc1f00-c77c-11ea-9161-b4b77e8c9d37.png)

They are currently implemented and being polished on the website: https://newsite.globaleaks.org/

**Comment by elioqoshi** [comment]
Here are the updated Brand Guidelines: [GlobaLeaks Brand Guidelines v5.pdf](https://github.com/uracreative/works/files/4932194/GlobaLeaks.Brand.Guidelines.v5.pdf)

**Comment by IfeanyiEkperi** [comment]
Awesome work

**Comment by AnXh3L0** [comment]
The illustrations have been implemented in the the new globaleaks.org website. This work is done.
