### ISSUE TITLE
REScala Brand Identity/Website design & Development.

### ISSUE THREAD

**Issue by rudolfburgaj** [uracreative/works#53]
We are developing the brand for a programming framework called REScala. Then we will be redesigning and developing in Jekyll the new website:
https://www.rescala-lang.com/

## Plan

-  After Annette and Mira provide us with the new name we will develop the brand: that includes logos, color palette, and typography. We will provide some various proposals afterward and apply the updated branding after approval.
- The next step is to create the mockups based on the sitemap wireframes and the branding applied.
- After various feedback iterations on the design, once it is signed off we will continue with the implementation of the Jekyll website based on the mockups specs in Figma.
- Potential bugs and issues on the website will be ironed out last.
- We should document how the website is set up and how content can be added and changed.

##  Team
@rudolfburgaj will be building out the wireframes and design mockups
@AnXh3L0 will be implementing the Jekyll website
@elioqoshi will be assisting on the branding process 

##  Timeline
We should aim to deliver the final deliverables latest by end of October.

**Comment by AnXh3L0** [comment]
The REScala website project is close to completion, current status is available in the following link: https://uracreative.github.io/rescala/ and a few screenshots following below.

![image](https://user-images.githubusercontent.com/25004151/99251714-1c09f580-280e-11eb-8b93-66281252a2fa.png)

![image](https://user-images.githubusercontent.com/25004151/99251732-22986d00-280e-11eb-838b-83540bb639b3.png)

![image](https://user-images.githubusercontent.com/25004151/99251787-347a1000-280e-11eb-9525-3be187e8e089.png)

**Comment by AnXh3L0** [comment]
This project has been completed and the assets have been delivered. The new website will be live soon over at https://www.rescala-lang.com
