### ISSUE TITLE
knurling-rs logo

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#54]
@jamesmunns from Ferrous Systems (Oxidize and Embedded Rust) reached out regarding a logo request for knurling-rs, a rust project (a joke on knurling, which helps to put an "ergonomic handle" on "bare metal").

They are expecting to launch a landing page soon and would like to have a logo for it and GitHub profiles, together with the color scheme for future usage. The typography used will be the same as Ferrous Systems uses overall (Rubik).

We are aiming for warm colors and try to move away from colder neutral colors here.

Context on the project:
https://github.com/knurling-rs/meta

**Comment by elioqoshi** [comment]
@jamesmunns 

Here is the first draft with 2 (similar) directions in different color schemes. A knurled (?) surface within the body of a cog or a bolt. These were the strongest visual metaphors in my view without overloading the logo with too many visual references.

Let me know which direction you prefer and what you might feel needs tweaked. 

Figma link:
https://www.figma.com/proto/6vw89Co6vtGVp7jIgJSHnc/knurling-rs?node-id=18%3A234&viewport=574%2C676%2C0.2570720613002777&scaling=min-zoom

![Light](https://user-images.githubusercontent.com/5436686/93390294-be891500-f86d-11ea-9528-527656639e44.jpg)

![Dark](https://user-images.githubusercontent.com/5436686/93390276-ba5cf780-f86d-11ea-85ad-7ab4be18236d.jpg)

**Comment by jamesmunns** [comment]
I'll give more feedback and share with the team tomorrow, but I *love* the "A" variant already, particularly with the dark background where you can see the color contrast.

**Comment by Lotterleben** [comment]
Personal opinion: Love it. I'm super enthusiastic about how the colours look on the dark surface! If we wanted to do a lighter theme I'd personally vote for something with a less stark contrast than a pure white background (maybe even a monochromatic approach?) if that makes sense design-wise. Regarding the logo versions, I like both :)

**Comment by elioqoshi** [comment]
@Lotterleben Thanks!

Good point regarding the background. Here are 2 examples in a light background in different corresponding colors.

![Color](https://user-images.githubusercontent.com/5436686/93456508-0fd0ed00-f8de-11ea-9fc4-f95a82a038f1.jpg)
![Light](https://user-images.githubusercontent.com/5436686/93456525-13fd0a80-f8de-11ea-8bfd-dac5e3b3893f.jpg)



We can play around with color application once we decide on which color theme would be preferred of course.

**Comment by jamesmunns** [comment]
Hey Elio, I'm not sure if we have a particular color scheme in mind, one of the things that you gave us for the Oxidize logo was a "palette" of colors, and it has been really useful to have when using the logo in different context.

For this, I don't think we need a single "canonical" color, if it wouldn't be too much trouble, I think we would appreciate a couple "complimentary colors" for each color of the logo?

For a more specific example, if we wanted to use "purple logo plus background color X" for one library, and "Pink logo plus background color Y" for a second library, and "Pink logo plus background color Z" for the docs of the second library, having a couple of go-to color combinations for us to paste in the CSS would be really handy to have.

IMO, I think we are good to lock in design A, and if it's not too much to ask for 3-4 good complimentary colors (for accents, backgrounds, contrast, etc.) for each flavor of the logo, that would be all we need to be ready to go! Let me know what you think or if I'm asking something out of scope.

**Comment by Mirabellensaft** [comment]
I really like the A variant of the logo too,  And +1 to the non-white background.

**Comment by elioqoshi** [comment]
@jamesmunns Sure happy to do that. I mean a logo can be flexible depending on application. So monochrome white and black is usually a given. Deciding what shades the color version will have is a priority. Of course there can be also colors which are not present in the actual logo but elsewhere in the brand, like on a landing page.

I experimented a bit with colors and came up with a landing page example (so it puts the colors into context) in a light and dark variation. What do you think? I think the magenta/purple combo works nicely and is in a similar spirit as Oxidize and async-std.

![Landing Page A](https://user-images.githubusercontent.com/5436686/93486189-31dd6600-f904-11ea-8b9b-5b7e5c028fb4.jpg)
![Landing Page B](https://user-images.githubusercontent.com/5436686/93486218-386bdd80-f904-11ea-8d28-6f26a06ad728.jpg)

**Comment by elioqoshi** [comment]
Here is also a Twitter example 
![Twitter](https://user-images.githubusercontent.com/5436686/93487322-6ef62800-f905-11ea-88d2-5a4db6ec85fa.jpg)

**Comment by jamesmunns** [comment]
It would be good to also see the Orange/Yellow one, and the colors you would pick for that. Maybe dark orange logo, light orange/yellow background, and a darker shade for the grid background?

I do like the Pink + Purple combo. I also like the background mesh pattern!

Speaking honestly, I'm probably not the right person stylistically to ask for color combos :sweat_smile:

Let me know if you want to have a quick zoom call at some point to just get a quick yes/no from me :)

**Comment by elioqoshi** [comment]
@jamesmunns Sure, here is a yellow/indigo combo:

![Landing Page C](https://user-images.githubusercontent.com/5436686/93565353-82e46d00-f98b-11ea-9f67-f6eba12d1661.jpg)

![Landing Page D](https://user-images.githubusercontent.com/5436686/93565215-457fdf80-f98b-11ea-801c-6473f352acbf.jpg)

I think both are viable alternatives, though I prefer the magenta/purple combo as it looks approachable, fun and warmer. If you have no reasons to go with any other specific colors, I'd recommend that. We can briefly talk over it on Zoom as well, sure!

**Comment by elioqoshi** [comment]
Here is a preview of the logo exports for the magenta option:
![image](https://user-images.githubusercontent.com/5436686/93565992-8cbaa000-f98c-11ea-9fdf-82dfc8adc05e.png)

**Comment by Lotterleben** [comment]
Personally, I think the Purple/Magenta combo is pretty, but in our context a bit too.. on the nose. While I am a big lover of all things pink (typing this wearing a pink dress sitting on a pink couch :D), this color combo calls to mind "we wanted to include women, so we made it pink!" tech initiatives which usually go wrong for a number of reasons and I wouldn't want knurling to evoke these kinds of associations.

(my personal favorite is the yellow color but at the end of the day I'd go with whatever @Mirabellensaft prefers.)

**Comment by elioqoshi** [comment]
@Lotterleben That's fair! My thinking was more on the ergonomical side of knurling patterns and making it very easy-going. Might have gone overboard though. The thing about magenta is that organizations are wary of it and go the safe route with blue and other cold colors. At the end of the day T-Mobile owns magenta and is able to not reflect a super feminine identity.

I am comfortable with going with the 2nd proposal though as well

**Comment by elioqoshi** [comment]
After having a call with @Mirabellensaft and @jamesmunns we experimented on some color schemes and layouts and came up with this style for both light and dark theme.

Let me know if you have any last thoughts, otherwise I will go ahead with exporting the assets on Monday for final delivery :)

![Finalist A](https://user-images.githubusercontent.com/5436686/93601002-ce653e00-f9c0-11ea-83ca-ea6cae40f2bb.jpg)
![Finalist B](https://user-images.githubusercontent.com/5436686/93601013-d3c28880-f9c0-11ea-956e-7d89b7ea6b5c.jpg)

**Comment by jamesmunns** [comment]
Hey @elioqoshi, consider it accepted from our side!

**Comment by elioqoshi** [comment]
@jamesmunns Great!

Here is the zip archive with the logos, colors and the diamond pattern.

You can also inspect the Figma file if you want to check out the landing page experimentations:
https://www.figma.com/file/6vw89Co6vtGVp7jIgJSHnc/knurling-rs?node-id=37%3A37
[knurling-rs.zip](https://github.com/uracreative/works/files/5249403/knurling-rs.zip)

**Comment by elioqoshi** [comment]
Closing this issue as this work has been finished. Thank you!
