### ISSUE TITLE
hessian.AI Landing Page

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#55]
Technical University of Darmstadt asked us to design a landing page for Hessian.AI, an academic center for Artificial Intelligence. Their current version is here:

https://ml-research.github.io/d2ai/index.html

I came up with a refresh and slightly better layout on Figma:
https://www.figma.com/file/V86kAEobFylOfSk5gpRn2m/Hessian.ai?node-id=3%3A278

Layout will be finished by Monday 21st September.
@SaptakS will do the implementation next week.

**Comment by elioqoshi** [comment]
The team decided to go wqith the light orange direction:
https://www.figma.com/file/V86kAEobFylOfSk5gpRn2m/Hessian.ai?node-id=7%3A6

![7](https://user-images.githubusercontent.com/5436686/93567646-4155c100-f98f-11ea-8427-7a8898bf10db.jpg)

Will do some more polishing on the layout and offer mobile layouts so @SaptakS can start development next week.

**Comment by elioqoshi** [comment]
We are going ahead with the purple/indigo theme.

![1](https://user-images.githubusercontent.com/5436686/93909207-d1816680-fcff-11ea-944e-9ad3a39140b4.jpg)

**Comment by AnXh3L0** [comment]
This project has been completed and is live at https://hessian.ai. Closing issue.
