### ISSUE TITLE
Rust LDN

### ISSUE THREAD

**Issue by gilescope** [uracreative/works#57]
Rust London is a meetup community of developers interested in the programming language. It
serves as a showcase for people already using it and for newcomers to meet in a casual
environment.
The purpose of Rust London is to create a space where people can present what they are
working on with Rust, and learn from each other.

## Our challenge:

The goal of the community is to grow - the community wants to reach out to more developers
and be as presentable as possible while doing it. The aim of the community is to stand in
prominence with other major tech communities like CloudNative and London Gophers. We also
want to grow our reach by creating a YouTube channel and need to have the fundamentals of a
branding language in place.

Where Will The Branding Be Used?
   * Twitter profile picture and cover flow Rust London Twitter - https://twitter.com/RustLdnUsers
   * YouTube Channel profile picture and cover flow - https://www.youtube.com/channel/UCJKVYbQ2iJkxPD0Hax-ohXg
   * Maybe a Facebook Page profile and cover flow?
   * Meetup.com Cover page Rust London Meetup Page -  https://www.meetup.com/Rust-London-User-Group/

(I'm sure you're well aware of the https://www.rust-lang.org/policies/media-guide given that you've done a lot of prior rust projects)

## Iconic

We're after something that visually makes it pretty clear around the world that we're both rusty & from London. Ideally something that can't be misconstrued to be a different city as that could be confusing. We were thinking big ben maybe? But we're not designers and our idea of what's iconic as londoners migth be different from what the rest of the world thinks of as iconic for london. This is where we really need your help.

**Comment by ergishkelzeni** [comment]
Hi @gilescope 

Ergi from Ura Design here. 
Glad to virtually meet you and happy to work on another Rust project.

I and @elioqoshi have been working on four logo directions for the Rust London community which are all a graphic combination of the Rust logo and British/London elements.

Logo proposals here:

[Rust_London_Logo_1.pdf](https://github.com/uracreative/works/files/5643736/Rust_London_Logo_1.pdf)
[Rust_London_Logo_2.pdf](https://github.com/uracreative/works/files/5643737/Rust_London_Logo_2.pdf)
[Rust_London_Logo_3.pdf](https://github.com/uracreative/works/files/5643738/Rust_London_Logo_3.pdf)
[Rust_London_Logo_4.pdf](https://github.com/uracreative/works/files/5643739/Rust_London_Logo_4.pdf)

Please, feel free to give any comments about the proposals and let us know if there is any preferred direction. 

After we set up the logo and the visual identity, we will be working on the deliverables mentioned in your message.

**Comment by gilescope** [comment]
I've talked with quite a few of the team and they are all very keen on option 3 (big ben). They love the font and the colours and the icon - this is great work - thank you!

**Comment by elioqoshi** [comment]
@gilescope That's very kind, thanks!

Should we go ahead and export the logo files for you?

**Comment by ergishkelzeni** [comment]
Thank you @gilescope! We are glad! 

As @elioqoshi mentioned, please let us know if you want us to export the logo files and meanwhile start exploring the visual language for the covers.

**Comment by gilescope** [comment]
Yes please - full steam ahead!

**Comment by ergishkelzeni** [comment]
Hi @gilescope 

You will find the branded images for Rust London [here](https://cloud.ura.design/s/Xk53DCCJn2zLbCj).

Included:
- Exported logo files (PNG/SVG)
- Avatars for the social media profiles mentioned above
- Various designed covers for the social media profiles mentioned above

Regarding the covers, we personally suggest using the last designed cover for each platform for a more unique style and identity, although all the covers are designed for Rust London.

Please, let us know if we can help with anything else!

**Comment by gilescope** [comment]
Really interesting cover designs! For the covers is there a figma `board` that you could share with us?

Will see sound them out with people - I _really _like quite a few of the ideas in the covers. Very striking.

**Comment by ergishkelzeni** [comment]
Hi @gilescope 

Figma link [here](https://www.figma.com/file/WZTHHbijn0rreJcOrrWUNB/Logo?node-id=45%3A0), containing the logos and the covers.
