### ISSUE TITLE
Team Community | Style & Accessibility Guidelines

### ISSUE THREAD

**Issue by ergishkelzeni** [uracreative/works#58]
We have been working with [Team Community](https://www.digitalrights.community/) to provide a visual identity for better accessibility, readability, and consistency in style. 

We helped with the colors, making sure the system we designed is flexible and offers colors for the logo, the text content and also in the supportive graphics. The new fonts also have a modern/funky character with the right readability. We also provided three new logos which keeping in mind the flexibility and accessibility. You can take a sneak peek at our [Figma files](https://www.figma.com/file/5DWl2hEqfzAwJa35x9o9BH/Digital-Rights-Community-Team-Style-Guide?node-id=10%3A494).

Now we are working with the style guide document, which will help to make sure the brand is presented correctly everywhere, while the team decides on the logo. 

Here's a mood board of random images taken from the brand exploration process:
![Team Community Workinprogress Image 3](https://user-images.githubusercontent.com/55448475/121358262-c2e0eb00-c932-11eb-9039-3fc47aa74958.png)

**Comment by elioqoshi** [comment]
We also finished the Event Calendar and Jobs board which you can find on Figma:

Jobs Board:
https://www.figma.com/file/5DWl2hEqfzAwJa35x9o9BH/Digital-Rights-Team-Community-Style-Guide?node-id=328%3A2896

Event Calendar:
https://www.figma.com/file/5DWl2hEqfzAwJa35x9o9BH/Digital-Rights-Team-Community-Style-Guide?node-id=401%3A772
