### ISSUE TITLE
Nextcoud Forms - Usability Evaluation

### ISSUE THREAD

**Issue by RenataGegaj** [uracreative/works#60]

**Comment by RenataGegaj** [comment]
## This is a summary of our usability research efforts on Nextcloud Forms 

**Phase 1: Heuristic Review**

In this first phase, we did a  heuristics review to surface common usability issues and shortcomings. This review included not only Nextcloud Forms, but also other parts of Nextcloud such as Talk, Sign up process, Docs, Tasks.

**Deliverables:**		
Find the report here: https://www.notion.so/Nextcloud-review-fb7f08a039244339a271550d842b8b1e


**Phase 2: User Interviews**

We conducted five 1h long interview sessions with people from a variety of backgrounds, to get valuable insights. We talked to users from rofessional backgrounds(IT, Arts, UX Researchers etc), computer literacy, Nextcloud/Forms usage. 
 Google Forms or TypeForm to understand if Nextcloud Forms is able to fulfill these requirements and what is missing to fill that gap. Based on the results of the heuristics review, we would conduct several interviews with researchers to detect shortcomings in the editor and submission view.


Deliverables:		
Editor user research results / usability report
Submission view user research results / usability report


Phase 3: Accessibility Report


The submission and editor view will be tested for accessibility shortcomings in reference to WCAG 2.0 AA standards. Tests will be conducted on Desktop and Mobile phone with a screen reader and exclusive keyboard controls. We will utilize automated accessibility testing software as well as manual testing.


Deliverables:		
Editor accessibility report & recommendations
Submission view accessibility report & recommendations



Phase 4: Design Mockups


Based on the results of the past phases, we will provide recommended design mockups to address possible usability and accessibility shortcomings as well as missing features. This work will be critical for future implementation and patches to the software.


Deliverables:		
Hi-Fi Figma Mockups / Prototypes
Report explaining the new proposed designs

**Comment by ridhwn** [comment]
Hi, im one of the enterprise user of nextcloud. Im happy to help if you need tester on nextcloud forms because we also been actively using it. We have a planned to have a business case with upload feature in the forms. If you need any help do let us know. thank you
