### ISSUE TITLE
Observation Shareout

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#68]

**Comment by elioqoshi** [comment]
@RenataGegaj I think this is closed, can you summarize?

**Comment by RenataGegaj** [comment]
Yes this one is closed. We met with the Totem team and discussed outcomes from the heuristic review. Here are the explorations we did: https://www.figma.com/file/VUZywvcD3jzZviOyo5Vqw4/Expert-Review?node-id=0%3A1
