### ISSUE TITLE
Brand Guidelines

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#70]

**Comment by ergishkelzeni** [comment]
After exploring and proposing a new visual style that helps in the improvement of the accessibility of the website and the brand identity of Totem Project in general, we built the Totem's Brand Book V. 01. This document holds the visual identity guidelines on how to use the essential brand assets based on the new style. It also ensures that Totem is correctly presented everywhere through its visuals.

The PDF file of Brand Book V. 01: [Totem Project - Brand Book v. 01.pdf](https://github.com/uracreative/works/files/7762188/Totem.Project.-.Brand.Book.v.01.pdf)

**Comment by elioqoshi** [comment]
We can close this for now and tackle any brand changes separately in the future.
