### ISSUE TITLE
Guided Installation Wizard UX

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#87]

**Comment by elioqoshi** [comment]
@RenataGegaj a progress update on this?

**Comment by RenataGegaj** [comment]
I have wrapped up the work on the installation wizard for the admin and the member users.
You can find the mockups here: https://www.figma.com/file/QX4C6HjyPcwI9hNyUtIWse/Stackspin-Wizard?node-id=0%3A1
@tingeber if you'd like to revisit this later I'm happy to jump on a call or feel free to leave your comments here/figma.
