### ISSUE TITLE
Website Portfolio Page

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#96]
We should add the CalyxOS work to our portfolio.

**Comment by ergishkelzeni** [comment]
@elioqoshi @axhakani I designed the portfolio page in our Figma project. I am changing the status "In Review", so please take a look at it.

**Comment by ergishkelzeni** [comment]
Ops, we do not have "In Review" here. :)

**Comment by elioqoshi** [comment]
@ergishkelzeni Thanks! Added an "In Review" status to the project.

**Comment by RidhamRj** [comment]
Sup?

**Comment by elioqoshi** [comment]
@ergishkelzeni @axhakani did a quick proofread review on the text, good to go I think! Thanks!
