### ISSUE TITLE
Information Architecture / Card Sorting workshop

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/works#97]

**Comment by RenataGegaj** [comment]
Together with CCT team members, we conducted an information architecture session for the new CCT website. We started by evaluating the current websites information layout and determining the direction for the new one.
I'm currently working on the prototypes for a few possible design directions and will share them soon.

**Comment by RenataGegaj** [comment]
Closing this issue as we wrapped up this phase. Here is a part of our work on IA for the site: https://www.figma.com/file/EaNYS04s4mzjnRlCNwML0K/Untitled?node-id=0%3A1
